(PARAMETER,TYPE,VALUE,ACTION)=range(4)

(XML_ATTR,XML_CDATA,PYTHON_GLOBAL)=range(3)
#reverse lookup
TYPE_DICT={XML_ATTR:'XML_ATTR',XML_CDATA:'XML_CDATA',PYTHON_GLOBAL:'PYTHON_GLOBAL'}

TYPE_DICT_REVERSE={v:k for k, v in TYPE_DICT.items()}

(FLOAT,INT,CUSTOM)=range(3)
#reverse lookup
VALUE_TYPE_DICT={FLOAT:'float',INT:'int',CUSTOM:'custom'}
VALUE_TYPE_DICT_REVERSE={v:k for k, v in VALUE_TYPE_DICT.items()}
