        
#include "ContactOrientationPlugin.h"

#include <CompuCell3D/Simulator.h>
using namespace CompuCell3D;

#include <BasicUtils/BasicPluginProxy.h>

BasicPluginProxy<Plugin, ContactOrientationPlugin>
contactOrientationProxy("ContactOrientation", "Autogenerated plugin - the author of the plugin should provide brief description here",
         &Simulator::pluginManager);
