

#include "CustomCellAttributeSteppable.h"
#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>
using namespace CompuCell3D;


auto customCellAttributeSteppableProxy = registerPlugin<Steppable, CustomCellAttributeSteppable>(
	"CustomCellAttributeSteppable",
	"Autogenerated steppeble - the author of the plugin should provide brief description here",
	&Simulator::steppableManager
);
