# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cdTypesDockWidget2.ui'
#
# Created: Mon Apr 23 16:14:09 2012
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_uiCDTypesDockWidget(object):
    def setupUi(self, uiCDTypesDockWidget):
        uiCDTypesDockWidget.setObjectName(_fromUtf8("uiCDTypesDockWidget"))
        uiCDTypesDockWidget.resize(633, 589)
        uiCDTypesDockWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.uiCDTypesTreeWidget = QtGui.QTreeWidget(self.dockWidgetContents)
        self.uiCDTypesTreeWidget.setGeometry(QtCore.QRect(0, 0, 361, 551))
        self.uiCDTypesTreeWidget.setMinimumSize(QtCore.QSize(160, 160))
        self.uiCDTypesTreeWidget.setObjectName(_fromUtf8("uiCDTypesTreeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.uiCDTypesTreeWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/typesEditorRegionTypeGreen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_0 = QtGui.QTreeWidgetItem(self.uiCDTypesTreeWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/typesEditorRegionTypeRed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2.setIcon(0, icon1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        uiCDTypesDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(uiCDTypesDockWidget)
        QtCore.QMetaObject.connectSlotsByName(uiCDTypesDockWidget)

    def retranslateUi(self, uiCDTypesDockWidget):
        uiCDTypesDockWidget.setWindowTitle(QtGui.QApplication.translate("uiCDTypesDockWidget", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "Region and Cell Types", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "Value", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.uiCDTypesTreeWidget.isSortingEnabled()
        self.uiCDTypesTreeWidget.setSortingEnabled(False)
        self.uiCDTypesTreeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell size in region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(0).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(0).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(0).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(0).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(0).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(0).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "region type use", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell types in region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "greenTypeOne", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(0).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "amount of cells", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(0).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(0).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "fraction of region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(0).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "0.25", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(0).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell volume (Potts)", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(0).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "greenTypeTwo", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(1).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "amount of cells", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(1).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(1).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "fraction of region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(1).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "0.25", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(1).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell volume (Potts)", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(1).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "greenTypeThree", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(2).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "amount of cells", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(2).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(2).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "fraction of region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(2).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(2).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell volume (Potts)", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(0).child(2).child(2).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "120", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell size in region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(0).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(0).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(0).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(0).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(0).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(0).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "region type use", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell types in region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "redTypeOne", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(0).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "amount of cells", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(0).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(0).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "fraction of region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(0).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "0.25", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(0).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell volume (Potts)", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(0).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "redTypeTwo", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(1).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "amount of cells", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(1).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(1).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "fraction of region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(1).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "0.25", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(1).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell volume (Potts)", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(1).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "redTypeThree", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(2).child(0).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "amount of cells", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(2).child(0).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(2).child(1).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "fraction of region", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(2).child(1).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(2).child(2).setText(0, QtGui.QApplication.translate("uiCDTypesDockWidget", "cell volume (Potts)", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.topLevelItem(1).child(2).child(2).child(2).setText(1, QtGui.QApplication.translate("uiCDTypesDockWidget", "120", None, QtGui.QApplication.UnicodeUTF8))
        self.uiCDTypesTreeWidget.setSortingEnabled(__sortingEnabled)

