# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C_Plus_Plus_Module_Dialog.ui'
#
# Created: Fri Sep 30 15:36:14 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_C_Plus_Plus_Module_Dialog(object):
    def setupUi(self, C_Plus_Plus_Module_Dialog):
        C_Plus_Plus_Module_Dialog.setObjectName(_fromUtf8("C_Plus_Plus_Module_Dialog"))
        C_Plus_Plus_Module_Dialog.resize(336, 251)
        self.verticalLayout_2 = QtGui.QVBoxLayout(C_Plus_Plus_Module_Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(C_Plus_Plus_Module_Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtGui.QLabel(C_Plus_Plus_Module_Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.moduleDirLE = QtGui.QLineEdit(C_Plus_Plus_Module_Dialog)
        self.moduleDirLE.setObjectName(_fromUtf8("moduleDirLE"))
        self.gridLayout.addWidget(self.moduleDirLE, 1, 1, 1, 1)
        self.moduleDirPB = QtGui.QPushButton(C_Plus_Plus_Module_Dialog)
        self.moduleDirPB.setObjectName(_fromUtf8("moduleDirPB"))
        self.gridLayout.addWidget(self.moduleDirPB, 1, 2, 1, 1)
        self.moduleCoreNameLE = QtGui.QLineEdit(C_Plus_Plus_Module_Dialog)
        self.moduleCoreNameLE.setObjectName(_fromUtf8("moduleCoreNameLE"))
        self.gridLayout.addWidget(self.moduleCoreNameLE, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.moduleTypeGB = QtGui.QGroupBox(C_Plus_Plus_Module_Dialog)
        self.moduleTypeGB.setObjectName(_fromUtf8("moduleTypeGB"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.moduleTypeGB)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pluginRB = QtGui.QRadioButton(self.moduleTypeGB)
        self.pluginRB.setChecked(True)
        self.pluginRB.setObjectName(_fromUtf8("pluginRB"))
        self.horizontalLayout_3.addWidget(self.pluginRB)
        self.steppableRB = QtGui.QRadioButton(self.moduleTypeGB)
        self.steppableRB.setObjectName(_fromUtf8("steppableRB"))
        self.horizontalLayout_3.addWidget(self.steppableRB)
        self.pythonWrapCB = QtGui.QCheckBox(self.moduleTypeGB)
        self.pythonWrapCB.setChecked(True)
        self.pythonWrapCB.setObjectName(_fromUtf8("pythonWrapCB"))
        self.horizontalLayout_3.addWidget(self.pythonWrapCB)
        self.verticalLayout_2.addWidget(self.moduleTypeGB)
        self.pluginFunctionalityGB = QtGui.QGroupBox(C_Plus_Plus_Module_Dialog)
        self.pluginFunctionalityGB.setObjectName(_fromUtf8("pluginFunctionalityGB"))
        self.verticalLayout = QtGui.QVBoxLayout(self.pluginFunctionalityGB)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.energyFcnCB = QtGui.QCheckBox(self.pluginFunctionalityGB)
        self.energyFcnCB.setChecked(True)
        self.energyFcnCB.setObjectName(_fromUtf8("energyFcnCB"))
        self.horizontalLayout_2.addWidget(self.energyFcnCB)
        self.latticeMonitorCB = QtGui.QCheckBox(self.pluginFunctionalityGB)
        self.latticeMonitorCB.setObjectName(_fromUtf8("latticeMonitorCB"))
        self.horizontalLayout_2.addWidget(self.latticeMonitorCB)
        self.stepperCB = QtGui.QCheckBox(self.pluginFunctionalityGB)
        self.stepperCB.setObjectName(_fromUtf8("stepperCB"))
        self.horizontalLayout_2.addWidget(self.stepperCB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.extraAttribCB = QtGui.QCheckBox(self.pluginFunctionalityGB)
        self.extraAttribCB.setObjectName(_fromUtf8("extraAttribCB"))
        self.verticalLayout.addWidget(self.extraAttribCB)
        self.verticalLayout_2.addWidget(self.pluginFunctionalityGB)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okPB = QtGui.QPushButton(C_Plus_Plus_Module_Dialog)
        self.okPB.setObjectName(_fromUtf8("okPB"))
        self.horizontalLayout.addWidget(self.okPB)
        self.cancelPB = QtGui.QPushButton(C_Plus_Plus_Module_Dialog)
        self.cancelPB.setObjectName(_fromUtf8("cancelPB"))
        self.horizontalLayout.addWidget(self.cancelPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(C_Plus_Plus_Module_Dialog)
        QtCore.QObject.connect(self.cancelPB, QtCore.SIGNAL(_fromUtf8("clicked()")), C_Plus_Plus_Module_Dialog.reject)
        QtCore.QObject.connect(self.steppableRB, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pluginFunctionalityGB.setHidden)
        QtCore.QMetaObject.connectSlotsByName(C_Plus_Plus_Module_Dialog)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.moduleCoreNameLE, self.moduleDirLE)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.moduleDirLE, self.moduleDirPB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.moduleDirPB, self.pluginRB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.pluginRB, self.steppableRB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.steppableRB, self.energyFcnCB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.energyFcnCB, self.latticeMonitorCB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.latticeMonitorCB, self.stepperCB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.stepperCB, self.extraAttribCB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.extraAttribCB, self.cancelPB)
        C_Plus_Plus_Module_Dialog.setTabOrder(self.cancelPB, self.okPB)

    def retranslateUi(self, C_Plus_Plus_Module_Dialog):
        C_Plus_Plus_Module_Dialog.setWindowTitle(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Generate CC3D C++ Module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Module Core Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Module Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.moduleDirPB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.moduleTypeGB.setTitle(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "C++ Module Type", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginRB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.steppableRB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Steppable", None, QtGui.QApplication.UnicodeUTF8))
        self.pythonWrapCB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Python Wrap", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginFunctionalityGB.setTitle(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Plugin Functionality", None, QtGui.QApplication.UnicodeUTF8))
        self.energyFcnCB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "EnergyFunction", None, QtGui.QApplication.UnicodeUTF8))
        self.latticeMonitorCB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "LatticeMonitor", None, QtGui.QApplication.UnicodeUTF8))
        self.stepperCB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Stepper", None, QtGui.QApplication.UnicodeUTF8))
        self.extraAttribCB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Attach cell attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.okPB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPB.setText(QtGui.QApplication.translate("C_Plus_Plus_Module_Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

