# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\parvaldlg.ui'
#
# Created: Thu Oct 17 12:57:30 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ParValDlg(object):
    def setupUi(self, ParValDlg):
        ParValDlg.setObjectName(_fromUtf8("ParValDlg"))
        ParValDlg.resize(269, 215)
        ParValDlg.setWindowTitle(QtGui.QApplication.translate("ParValDlg", "Generate Parameter Values", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(ParValDlg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(ParValDlg)
        self.label.setText(QtGui.QApplication.translate("ParValDlg", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.minLE = QtGui.QLineEdit(ParValDlg)
        self.minLE.setObjectName(_fromUtf8("minLE"))
        self.gridLayout.addWidget(self.minLE, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(ParValDlg)
        self.label_2.setText(QtGui.QApplication.translate("ParValDlg", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.maxLE = QtGui.QLineEdit(ParValDlg)
        self.maxLE.setObjectName(_fromUtf8("maxLE"))
        self.gridLayout.addWidget(self.maxLE, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(ParValDlg)
        self.label_3.setText(QtGui.QApplication.translate("ParValDlg", "Number of Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.stepsLE = QtGui.QLineEdit(ParValDlg)
        self.stepsLE.setText(QtGui.QApplication.translate("ParValDlg", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsLE.setObjectName(_fromUtf8("stepsLE"))
        self.gridLayout.addWidget(self.stepsLE, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(ParValDlg)
        self.label_4.setText(QtGui.QApplication.translate("ParValDlg", "Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.distrCB = QtGui.QComboBox(ParValDlg)
        self.distrCB.setObjectName(_fromUtf8("distrCB"))
        self.distrCB.addItem(_fromUtf8(""))
        self.distrCB.setItemText(0, QtGui.QApplication.translate("ParValDlg", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.distrCB.addItem(_fromUtf8(""))
        self.distrCB.setItemText(1, QtGui.QApplication.translate("ParValDlg", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.distrCB.addItem(_fromUtf8(""))
        self.distrCB.setItemText(2, QtGui.QApplication.translate("ParValDlg", "random", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.distrCB, 3, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(ParValDlg)
        self.label_6.setText(QtGui.QApplication.translate("ParValDlg", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.typeCB = QtGui.QComboBox(ParValDlg)
        self.typeCB.setObjectName(_fromUtf8("typeCB"))
        self.typeCB.addItem(_fromUtf8(""))
        self.typeCB.setItemText(0, QtGui.QApplication.translate("ParValDlg", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCB.addItem(_fromUtf8(""))
        self.typeCB.setItemText(1, QtGui.QApplication.translate("ParValDlg", "int", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCB.addItem(_fromUtf8(""))
        self.typeCB.setItemText(2, QtGui.QApplication.translate("ParValDlg", "string", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.typeCB, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(ParValDlg)
        self.label_5.setText(QtGui.QApplication.translate("ParValDlg", "Values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.valuesLE = QtGui.QLineEdit(ParValDlg)
        self.valuesLE.setObjectName(_fromUtf8("valuesLE"))
        self.horizontalLayout_6.addWidget(self.valuesLE)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.generatePB = QtGui.QPushButton(ParValDlg)
        self.generatePB.setText(QtGui.QApplication.translate("ParValDlg", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.generatePB.setObjectName(_fromUtf8("generatePB"))
        self.horizontalLayout_7.addWidget(self.generatePB)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.pushButton_2 = QtGui.QPushButton(ParValDlg)
        self.pushButton_2.setText(QtGui.QApplication.translate("ParValDlg", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(ParValDlg)
        self.pushButton.setText(QtGui.QApplication.translate("ParValDlg", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(ParValDlg)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), ParValDlg.reject)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ParValDlg.accept)
        QtCore.QMetaObject.connectSlotsByName(ParValDlg)

    def retranslateUi(self, ParValDlg):
        pass

