

#include "FieldManager.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;


auto fieldManagerProxy = registerPlugin<Steppable,FieldManager>(
	"FieldManager", 
	"Autogenerated steppeble - the author of the steppeble should provide brief description here", 
	&Simulator::steppableManager
);

