#include "ImplicitMotilityPlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto implicitMotilityProxy = registerPlugin<Plugin, ImplicitMotilityPlugin>(
    "ImplicitMotility", 
    "Autogenerated plugin - the author of the plugin should provide brief description here",
    &Simulator::pluginManager
);
