version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - python cc3d/doc/code_ref/developer/build/build.py
      - python cc3d/doc/code_ref/user/build/build.py

conda:
  environment: cc3d/doc/environment.yaml
