#include "OrientedGrowthPlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto orientedGrowthProxy = registerPlugin<Plugin, OrientedGrowthPlugin>(
        "OrientedGrowth",
        "Autogenerated plugin - the author of the plugin should provide brief description here",
        &Simulator::pluginManager
);
