        

#include "VectorFieldPolarizationPlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;


auto vectorFieldPolarizationProxy = registerPlugin<Plugin,VectorFieldPolarizationPlugin>(
	"VectorFieldPolarization", 
	"Autogenerated plugin - the author of the plugin should provide brief description here", 
	&Simulator::pluginManager
);


