

#include "HeterotypicBoundaryLength.h"



#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>
using namespace CompuCell3D;


auto heterotypicBoundaryLengthProxy = registerPlugin<Steppable, HeterotypicBoundaryLength>(
	"HeterotypicBoundaryLength",
	"Autogenerated steppeble - the author of the plugin should provide brief description here",
	&Simulator::steppableManager
);

//BasicPluginProxy<Steppable, HeterotypicBoundaryLength>
//
//heterotypicBoundaryLengthProxy("HeterotypicBoundaryLength", "Autogenerated steppeble - the author of the plugin should provide brief description here",
//
//	    &Simulator::steppableManager);
//
//
//
//#include "VolumeTrackerPlugin.h"
//
//#include <CompuCell3D/Simulator.h>
//
//
//using namespace CompuCell3D;
//
//auto volumeTrackerProxy = registerPlugin<Plugin, VolumeTrackerPlugin>(
//	"VolumeTracker",
//	"Tracks cell volumes",
//	&Simulator::pluginManager
//);
