#include "CellTypeMonitorPlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto cellTypeMonitorProxy = registerPlugin<Plugin, CellTypeMonitorPlugin>(
        "CellTypeMonitor",
        "Autogenerated plugin - the author of the plugin should provide brief description here",
        &Simulator::pluginManager
);
