import vtk
sphere = vtk.vtkSphereSource()
elevation = vtk.vtkElevationFilter()
elevation.SetInputConnection(sphere.GetOutputPort())
elevation.SetLowPoint(-1,0,0)
elevation.SetHighPoint(1,0,0)

source1 = vtk.vtkImageCanvasSource2D()
source1.SetScalarTypeToUnsignedChar()
source1.SetNumberOfScalarComponents(3)
source1.SetExtent(0, 100, 0, 100, 0, 0)
source1.SetDrawColor(0, 0, 0, 1)
source1.FillBox(0, 100, 0, 100)
source1.SetDrawColor(255, 0, 0, 1)
source1.FillBox(10, 20, 10, 20)
source1.FillBox(40, 50, 20, 30)
source1.Update()

p2c = vtk.vtkPointDataToCellData()
p2c.SetInputConnection(source1.GetOutputPort())
# stripper = vtk.vtkStripper()
# stripper.SetInputConnection(p2c.GetOutputPort())
# stripper.PassCellDataAsFieldDataOn()
sphereMapper = vtk.vtkPolyDataMapper()
# sphereMapper.SetInputConnection(stripper.GetOutputPort())
# sphereMapper.SetInputConnection(sphere.GetOutputPort())
sphereMapper.SetInputConnection(p2c.GetOutputPort())

# sphereMapper.SelectColorArray("Elevation")
# sphereMapper.SetColorModeToMapScalars()
# sphereMapper.SetScalarModeToUseFieldData()
# sphereMapper.SetScalarRange(0.28,0.72)
sphereActor = vtk.vtkActor()
sphereActor.SetMapper(sphereMapper)
#interpolation must be set to flat for cell colors to work
#for triangle strips.
sphereActor.GetProperty().SetInterpolationToFlat()

ren1 = vtk.vtkRenderer()
ren1.AddActor(sphereActor)
# renWin = vtk.vtkRenderWindow()
# renWin.AddRenderer(ren1)
# renWin.SetSize(200,200)
# iren = vtk.vtkRenderWindowInteractor()
# iren.SetRenderWindow(renWin)
# renWin.Render()
renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren1)

renderWindowInteractor = vtk.vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renWin)

ren1.AddActor(sphereActor)
# ren1.SetBackground(colors.GetColor3d("white"))  # Background color white
renWin.Render()
renderWindowInteractor.Start()
