#include "OrientedGrowth2Plugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto orientedGrowth2Proxy = registerPlugin<Plugin, OrientedGrowth2Plugin>(
    "OrientedGrowth2", 
    "Autogenerated plugin - the author of the plugin should provide brief description here",
    &Simulator::pluginManager
);
