

#include "PolygonInitializer.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;


auto polygonInitializerProxy = registerPlugin<Steppable,PolygonInitializer>(
	"PolygonInitializer", 
	"Autogenerated steppeble - the author of the steppeble should provide brief description here", 
	&Simulator::steppableManager
);

