from cc3d import CompuCellSetup

from DiffusionSolverFE_OpenCL_3DSteppables import DiffusionSolverFE_OpenCL_3DSteppable

CompuCellSetup.register_steppable(steppable=DiffusionSolverFE_OpenCL_3DSteppable(frequency=1))

CompuCellSetup.run()
