# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cc3D_prefs9.ui'
#
# Created: Mon Aug 27 09:11:14 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CC3DPrefs(object):
    def setupUi(self, CC3DPrefs):
        CC3DPrefs.setObjectName(_fromUtf8("CC3DPrefs"))
        CC3DPrefs.resize(656, 570)
        self.verticalLayout_11 = QtGui.QVBoxLayout(CC3DPrefs)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.tabWidget = QtGui.QTabWidget(CC3DPrefs)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_output = QtGui.QWidget()
        self.tab_output.setObjectName(_fromUtf8("tab_output"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_output)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.tab_output)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.updateScreenSpinBox = QtGui.QSpinBox(self.tab_output)
        self.updateScreenSpinBox.setMinimum(1)
        self.updateScreenSpinBox.setMaximum(1000000000)
        self.updateScreenSpinBox.setObjectName(_fromUtf8("updateScreenSpinBox"))
        self.horizontalLayout_3.addWidget(self.updateScreenSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.outputImagesCheckBox = QtGui.QCheckBox(self.tab_output)
        self.outputImagesCheckBox.setObjectName(_fromUtf8("outputImagesCheckBox"))
        self.horizontalLayout_15.addWidget(self.outputImagesCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.saveImageSpinBox = QtGui.QSpinBox(self.tab_output)
        self.saveImageSpinBox.setMinimum(1)
        self.saveImageSpinBox.setMaximum(1000000000)
        self.saveImageSpinBox.setObjectName(_fromUtf8("saveImageSpinBox"))
        self.horizontalLayout_15.addWidget(self.saveImageSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.outputLatticeDataCheckBox = QtGui.QCheckBox(self.tab_output)
        self.outputLatticeDataCheckBox.setObjectName(_fromUtf8("outputLatticeDataCheckBox"))
        self.horizontalLayout_14.addWidget(self.outputLatticeDataCheckBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.saveLatticeSpinBox = QtGui.QSpinBox(self.tab_output)
        self.saveLatticeSpinBox.setMinimum(1)
        self.saveLatticeSpinBox.setMaximum(1000000000)
        self.saveLatticeSpinBox.setObjectName(_fromUtf8("saveLatticeSpinBox"))
        self.horizontalLayout_14.addWidget(self.saveLatticeSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16.addLayout(self.verticalLayout_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.line = QtGui.QFrame(self.tab_output)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_10.addWidget(self.line)
        self.useInternalConsoleCheckBox = QtGui.QCheckBox(self.tab_output)
        self.useInternalConsoleCheckBox.setObjectName(_fromUtf8("useInternalConsoleCheckBox"))
        self.verticalLayout_10.addWidget(self.useInternalConsoleCheckBox)
        self.closePlayerCheckBox = QtGui.QCheckBox(self.tab_output)
        self.closePlayerCheckBox.setObjectName(_fromUtf8("closePlayerCheckBox"))
        self.verticalLayout_10.addWidget(self.closePlayerCheckBox)
        self.line_2 = QtGui.QFrame(self.tab_output)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_10.addWidget(self.line_2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.projectLocationLineEdit = QtGui.QLineEdit(self.tab_output)
        self.projectLocationLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projectLocationLineEdit.setText(_fromUtf8(""))
        self.projectLocationLineEdit.setObjectName(_fromUtf8("projectLocationLineEdit"))
        self.gridLayout_6.addWidget(self.projectLocationLineEdit, 0, 0, 1, 1)
        self.projectLocationButton = QtGui.QPushButton(self.tab_output)
        self.projectLocationButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.projectLocationButton.setAutoDefault(False)
        self.projectLocationButton.setObjectName(_fromUtf8("projectLocationButton"))
        self.gridLayout_6.addWidget(self.projectLocationButton, 0, 1, 1, 3)
        self.outputLocationLineEdit = QtGui.QLineEdit(self.tab_output)
        self.outputLocationLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outputLocationLineEdit.setObjectName(_fromUtf8("outputLocationLineEdit"))
        self.gridLayout_6.addWidget(self.outputLocationLineEdit, 1, 0, 1, 1)
        self.outputLocationButton = QtGui.QPushButton(self.tab_output)
        self.outputLocationButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.outputLocationButton.setAutoDefault(False)
        self.outputLocationButton.setObjectName(_fromUtf8("outputLocationButton"))
        self.gridLayout_6.addWidget(self.outputLocationButton, 1, 1, 1, 2)
        self.outputToProjectCheckBox = QtGui.QCheckBox(self.tab_output)
        self.outputToProjectCheckBox.setObjectName(_fromUtf8("outputToProjectCheckBox"))
        self.gridLayout_6.addWidget(self.outputToProjectCheckBox, 1, 3, 1, 1)
        self.prefsFileLineEdit = QtGui.QLineEdit(self.tab_output)
        self.prefsFileLineEdit.setObjectName(_fromUtf8("prefsFileLineEdit"))
        self.gridLayout_6.addWidget(self.prefsFileLineEdit, 2, 0, 1, 2)
        self.prefsFileButton = QtGui.QPushButton(self.tab_output)
        self.prefsFileButton.setObjectName(_fromUtf8("prefsFileButton"))
        self.gridLayout_6.addWidget(self.prefsFileButton, 2, 2, 1, 2)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.verticalLayout_14.addLayout(self.verticalLayout_10)
        spacerItem4 = QtGui.QSpacerItem(20, 119, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_output, _fromUtf8(""))
        self.tab_cell_type = QtGui.QWidget()
        self.tab_cell_type.setObjectName(_fromUtf8("tab_cell_type"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_cell_type)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 20, 240, 341))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(141, 341))
        self.groupBox_10.setMaximumSize(QtCore.QSize(240, 341))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.selectCellColorLabel = QtGui.QLabel(self.groupBox_10)
        self.selectCellColorLabel.setTextFormat(QtCore.Qt.PlainText)
        self.selectCellColorLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.selectCellColorLabel.setWordWrap(True)
        self.selectCellColorLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.selectCellColorLabel.setObjectName(_fromUtf8("selectCellColorLabel"))
        self.verticalLayout_6.addWidget(self.selectCellColorLabel)
        self.typeColorTable = QtGui.QTableWidget(self.groupBox_10)
        self.typeColorTable.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeColorTable.sizePolicy().hasHeightForWidth())
        self.typeColorTable.setSizePolicy(sizePolicy)
        self.typeColorTable.setMinimumSize(QtCore.QSize(200, 0))
        self.typeColorTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.typeColorTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.typeColorTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.typeColorTable.setIconSize(QtCore.QSize(0, 0))
        self.typeColorTable.setShowGrid(True)
        self.typeColorTable.setWordWrap(False)
        self.typeColorTable.setCornerButtonEnabled(False)
        self.typeColorTable.setRowCount(20)
        self.typeColorTable.setColumnCount(3)
        self.typeColorTable.setObjectName(_fromUtf8("typeColorTable"))
        self.typeColorTable.setColumnCount(3)
        self.typeColorTable.setRowCount(20)
        item = QtGui.QTableWidgetItem()
        self.typeColorTable.setItem(0, 1, item)
        self.typeColorTable.horizontalHeader().setVisible(False)
        self.typeColorTable.horizontalHeader().setCascadingSectionResizes(True)
        self.typeColorTable.horizontalHeader().setDefaultSectionSize(50)
        self.typeColorTable.horizontalHeader().setHighlightSections(False)
        self.typeColorTable.verticalHeader().setVisible(False)
        self.typeColorTable.verticalHeader().setDefaultSectionSize(18)
        self.typeColorTable.verticalHeader().setHighlightSections(False)
        self.typeColorTable.verticalHeader().setMinimumSectionSize(11)
        self.typeColorTable.verticalHeader().setSortIndicatorShown(True)
        self.typeColorTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.typeColorTable)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.addCellTypeButton = QtGui.QPushButton(self.groupBox_10)
        self.addCellTypeButton.setEnabled(True)
        self.addCellTypeButton.setAutoDefault(False)
        self.addCellTypeButton.setDefault(False)
        self.addCellTypeButton.setObjectName(_fromUtf8("addCellTypeButton"))
        self.horizontalLayout_13.addWidget(self.addCellTypeButton)
        self.deleteCellTypeButton = QtGui.QPushButton(self.groupBox_10)
        self.deleteCellTypeButton.setEnabled(False)
        self.deleteCellTypeButton.setAutoDefault(False)
        self.deleteCellTypeButton.setObjectName(_fromUtf8("deleteCellTypeButton"))
        self.horizontalLayout_13.addWidget(self.deleteCellTypeButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_cell_type)
        self.groupBox_4.setGeometry(QtCore.QRect(290, 220, 191, 151))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 161, 121))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cellGlyphScaleByVolumeCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.cellGlyphScaleByVolumeCheckBox.setObjectName(_fromUtf8("cellGlyphScaleByVolumeCheckBox"))
        self.verticalLayout_5.addWidget(self.cellGlyphScaleByVolumeCheckBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.cellGlyphScale = QtGui.QLineEdit(self.layoutWidget)
        self.cellGlyphScale.setObjectName(_fromUtf8("cellGlyphScale"))
        self.gridLayout.addWidget(self.cellGlyphScale, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.cellGlyphThetaRes = QtGui.QSpinBox(self.layoutWidget)
        self.cellGlyphThetaRes.setObjectName(_fromUtf8("cellGlyphThetaRes"))
        self.gridLayout.addWidget(self.cellGlyphThetaRes, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.cellGlyphPhiRes = QtGui.QSpinBox(self.layoutWidget)
        self.cellGlyphPhiRes.setObjectName(_fromUtf8("cellGlyphPhiRes"))
        self.gridLayout.addWidget(self.cellGlyphPhiRes, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_cell_type)
        self.groupBox_11.setGeometry(QtCore.QRect(290, 30, 181, 171))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 33, 163, 130))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.borderColorLabel = QtGui.QLabel(self.layoutWidget1)
        self.borderColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.borderColorLabel.setObjectName(_fromUtf8("borderColorLabel"))
        self.gridLayout_2.addWidget(self.borderColorLabel, 0, 0, 1, 1)
        self.cellBorderColorButton = QtGui.QToolButton(self.layoutWidget1)
        self.cellBorderColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.cellBorderColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.cellBorderColorButton.setText(_fromUtf8(""))
        self.cellBorderColorButton.setObjectName(_fromUtf8("cellBorderColorButton"))
        self.gridLayout_2.addWidget(self.cellBorderColorButton, 0, 1, 1, 1)
        self.clusterBorderColorLabel = QtGui.QLabel(self.layoutWidget1)
        self.clusterBorderColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clusterBorderColorLabel.setObjectName(_fromUtf8("clusterBorderColorLabel"))
        self.gridLayout_2.addWidget(self.clusterBorderColorLabel, 1, 0, 1, 1)
        self.clusterBorderColorButton = QtGui.QToolButton(self.layoutWidget1)
        self.clusterBorderColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.clusterBorderColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.clusterBorderColorButton.setText(_fromUtf8(""))
        self.clusterBorderColorButton.setObjectName(_fromUtf8("clusterBorderColorButton"))
        self.gridLayout_2.addWidget(self.clusterBorderColorButton, 1, 1, 1, 1)
        self.contourColorLabel = QtGui.QLabel(self.layoutWidget1)
        self.contourColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contourColorLabel.setObjectName(_fromUtf8("contourColorLabel"))
        self.gridLayout_2.addWidget(self.contourColorLabel, 2, 0, 1, 1)
        self.contourColorButton = QtGui.QToolButton(self.layoutWidget1)
        self.contourColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.contourColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.contourColorButton.setText(_fromUtf8(""))
        self.contourColorButton.setObjectName(_fromUtf8("contourColorButton"))
        self.gridLayout_2.addWidget(self.contourColorButton, 2, 1, 1, 1)
        self.windowColorLabel = QtGui.QLabel(self.layoutWidget1)
        self.windowColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.windowColorLabel.setObjectName(_fromUtf8("windowColorLabel"))
        self.gridLayout_2.addWidget(self.windowColorLabel, 3, 0, 1, 1)
        self.windowColorButton = QtGui.QToolButton(self.layoutWidget1)
        self.windowColorButton.setEnabled(True)
        self.windowColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.windowColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.windowColorButton.setText(_fromUtf8(""))
        self.windowColorButton.setObjectName(_fromUtf8("windowColorButton"))
        self.gridLayout_2.addWidget(self.windowColorButton, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_cell_type, _fromUtf8(""))
        self.tab_field = QtGui.QWidget()
        self.tab_field.setObjectName(_fromUtf8("tab_field"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_field)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.tab_field)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.fieldComboBox = QtGui.QComboBox(self.tab_field)
        self.fieldComboBox.setObjectName(_fromUtf8("fieldComboBox"))
        self.horizontalLayout_5.addWidget(self.fieldComboBox)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.line_3 = QtGui.QFrame(self.tab_field)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_15.addWidget(self.line_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.fieldMinLabel = QtGui.QLabel(self.groupBox_8)
        self.fieldMinLabel.setObjectName(_fromUtf8("fieldMinLabel"))
        self.gridLayout_11.addWidget(self.fieldMinLabel, 0, 0, 1, 1)
        self.fieldMinRange = QtGui.QLineEdit(self.groupBox_8)
        self.fieldMinRange.setObjectName(_fromUtf8("fieldMinRange"))
        self.gridLayout_11.addWidget(self.fieldMinRange, 0, 1, 1, 1)
        self.fieldMinRangeFixedCheckBox = QtGui.QCheckBox(self.groupBox_8)
        self.fieldMinRangeFixedCheckBox.setObjectName(_fromUtf8("fieldMinRangeFixedCheckBox"))
        self.gridLayout_11.addWidget(self.fieldMinRangeFixedCheckBox, 0, 2, 1, 1)
        self.fieldMaxLabel = QtGui.QLabel(self.groupBox_8)
        self.fieldMaxLabel.setObjectName(_fromUtf8("fieldMaxLabel"))
        self.gridLayout_11.addWidget(self.fieldMaxLabel, 1, 0, 1, 1)
        self.fieldMaxRange = QtGui.QLineEdit(self.groupBox_8)
        self.fieldMaxRange.setObjectName(_fromUtf8("fieldMaxRange"))
        self.gridLayout_11.addWidget(self.fieldMaxRange, 1, 1, 1, 1)
        self.fieldMaxRangeFixedCheckBox = QtGui.QCheckBox(self.groupBox_8)
        self.fieldMaxRangeFixedCheckBox.setObjectName(_fromUtf8("fieldMaxRangeFixedCheckBox"))
        self.gridLayout_11.addWidget(self.fieldMaxRangeFixedCheckBox, 1, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_11)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        self.label_18.setMinimumSize(QtCore.QSize(0, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_20.addWidget(self.label_18)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.vectorsArrowLength = QtGui.QSpinBox(self.groupBox_9)
        self.vectorsArrowLength.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsArrowLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vectorsArrowLength.setMaximum(9999)
        self.vectorsArrowLength.setObjectName(_fromUtf8("vectorsArrowLength"))
        self.horizontalLayout_20.addWidget(self.vectorsArrowLength)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.vectorsScaleArrowCheckBox = QtGui.QCheckBox(self.groupBox_9)
        self.vectorsScaleArrowCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsScaleArrowCheckBox.setObjectName(_fromUtf8("vectorsScaleArrowCheckBox"))
        self.horizontalLayout_19.addWidget(self.vectorsScaleArrowCheckBox)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.vectorsArrowColorCheckBox = QtGui.QCheckBox(self.groupBox_9)
        self.vectorsArrowColorCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsArrowColorCheckBox.setObjectName(_fromUtf8("vectorsArrowColorCheckBox"))
        self.horizontalLayout_18.addWidget(self.vectorsArrowColorCheckBox)
        self.vectorsArrowColorButton = QtGui.QToolButton(self.groupBox_9)
        self.vectorsArrowColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.vectorsArrowColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.vectorsArrowColorButton.setText(_fromUtf8(""))
        self.vectorsArrowColorButton.setObjectName(_fromUtf8("vectorsArrowColorButton"))
        self.horizontalLayout_18.addWidget(self.vectorsArrowColorButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.vectorsOverlayCheckBox = QtGui.QCheckBox(self.tab_field)
        self.vectorsOverlayCheckBox.setObjectName(_fromUtf8("vectorsOverlayCheckBox"))
        self.verticalLayout_2.addWidget(self.vectorsOverlayCheckBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.fieldLegendNumLabels = QtGui.QSpinBox(self.groupBox_7)
        self.fieldLegendNumLabels.setMinimumSize(QtCore.QSize(0, 30))
        self.fieldLegendNumLabels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fieldLegendNumLabels.setMaximum(9999)
        self.fieldLegendNumLabels.setObjectName(_fromUtf8("fieldLegendNumLabels"))
        self.horizontalLayout_7.addWidget(self.fieldLegendNumLabels)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.fieldLegendAccuracy = QtGui.QSpinBox(self.groupBox_7)
        self.fieldLegendAccuracy.setMinimumSize(QtCore.QSize(0, 30))
        self.fieldLegendAccuracy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fieldLegendAccuracy.setMaximum(9999)
        self.fieldLegendAccuracy.setObjectName(_fromUtf8("fieldLegendAccuracy"))
        self.horizontalLayout_8.addWidget(self.fieldLegendAccuracy)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.fieldShowLegendCheckBox = QtGui.QCheckBox(self.groupBox_7)
        self.fieldShowLegendCheckBox.setObjectName(_fromUtf8("fieldShowLegendCheckBox"))
        self.horizontalLayout_9.addWidget(self.fieldShowLegendCheckBox)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.gridLayout_7.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.numIsovalsInRangeLabel = QtGui.QLabel(self.groupBox_12)
        self.numIsovalsInRangeLabel.setObjectName(_fromUtf8("numIsovalsInRangeLabel"))
        self.gridLayout_10.addWidget(self.numIsovalsInRangeLabel, 1, 0, 1, 1)
        self.numberOfContoursLinesSpinBox = QtGui.QSpinBox(self.groupBox_12)
        self.numberOfContoursLinesSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfContoursLinesSpinBox.setMaximum(9999)
        self.numberOfContoursLinesSpinBox.setObjectName(_fromUtf8("numberOfContoursLinesSpinBox"))
        self.gridLayout_10.addWidget(self.numberOfContoursLinesSpinBox, 1, 1, 1, 1)
        self.isovalList = QtGui.QLineEdit(self.groupBox_12)
        self.isovalList.setObjectName(_fromUtf8("isovalList"))
        self.gridLayout_10.addWidget(self.isovalList, 0, 1, 1, 1)
        self.isovalLabel = QtGui.QLabel(self.groupBox_12)
        self.isovalLabel.setObjectName(_fromUtf8("isovalLabel"))
        self.gridLayout_10.addWidget(self.isovalLabel, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_15)
        self.tabWidget.addTab(self.tab_field, _fromUtf8(""))
        self.tab_3D = QtGui.QWidget()
        self.tab_3D.setObjectName(_fromUtf8("tab_3D"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_3D)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem12 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.groupBox = QtGui.QGroupBox(self.tab_3D)
        self.groupBox.setEnabled(False)
        self.groupBox.setMinimumSize(QtCore.QSize(110, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 91, 112))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox.setMinimumSize(QtCore.QSize(25, 30))
        self.spinBox.setSpecialValueText(_fromUtf8(""))
        self.spinBox.setMaximum(999)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_5.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_2.setMaximum(999)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_5.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.layoutWidget2)
        self.spinBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_3.setMaximum(999)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_5.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem13 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3D)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_6.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_6.setSpecialValueText(_fromUtf8(""))
        self.spinBox_6.setMaximum(999)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_3.addWidget(self.spinBox_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_7.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_7.setMaximum(999)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_3.addWidget(self.spinBox_7, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_8.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_8.setMaximum(999)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout_3.addWidget(self.spinBox_8, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        spacerItem14 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3D)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(2, 1, 2, 1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cellTypesInvisibleList = QtGui.QLineEdit(self.groupBox_2)
        self.cellTypesInvisibleList.setObjectName(_fromUtf8("cellTypesInvisibleList"))
        self.horizontalLayout.addWidget(self.cellTypesInvisibleList)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.boundingBoxCheckBox = QtGui.QCheckBox(self.tab_3D)
        self.boundingBoxCheckBox.setObjectName(_fromUtf8("boundingBoxCheckBox"))
        self.horizontalLayout_10.addWidget(self.boundingBoxCheckBox)
        self.label_12 = QtGui.QLabel(self.tab_3D)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.boundingBoxColorButton = QtGui.QToolButton(self.tab_3D)
        self.boundingBoxColorButton.setEnabled(True)
        self.boundingBoxColorButton.setText(_fromUtf8(""))
        self.boundingBoxColorButton.setObjectName(_fromUtf8("boundingBoxColorButton"))
        self.horizontalLayout_10.addWidget(self.boundingBoxColorButton)
        spacerItem15 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem16 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_3D, _fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.tabWidget)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.buttonBox = QtGui.QDialogButtonBox(CC3DPrefs)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_11.addWidget(self.buttonBox)

        self.retranslateUi(CC3DPrefs)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CC3DPrefs.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CC3DPrefs.reject)
        QtCore.QMetaObject.connectSlotsByName(CC3DPrefs)

    def retranslateUi(self, CC3DPrefs):
        CC3DPrefs.setWindowTitle(QtGui.QApplication.translate("CC3DPrefs", "CC3D Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CC3DPrefs", "Update screen every Nth MCS", None, QtGui.QApplication.UnicodeUTF8))
        self.outputImagesCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Save image every Nth MCS", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLatticeDataCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Save lattice every Nth MCS", None, QtGui.QApplication.UnicodeUTF8))
        self.useInternalConsoleCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Use internal console for text output", None, QtGui.QApplication.UnicodeUTF8))
        self.closePlayerCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Close Player after simulation ends", None, QtGui.QApplication.UnicodeUTF8))
        self.projectLocationButton.setText(QtGui.QApplication.translate("CC3DPrefs", "Project Location", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLocationButton.setText(QtGui.QApplication.translate("CC3DPrefs", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.outputToProjectCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "=Project", None, QtGui.QApplication.UnicodeUTF8))
        self.prefsFileButton.setText(QtGui.QApplication.translate("CC3DPrefs", "Preferences File", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_output), QtGui.QApplication.translate("CC3DPrefs", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Cell Types and Colors", None, QtGui.QApplication.UnicodeUTF8))
        self.selectCellColorLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Select a row in the table to change that cell type color.   Type        Name           Color", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.typeColorTable.isSortingEnabled()
        self.typeColorTable.setSortingEnabled(False)
        self.typeColorTable.setSortingEnabled(__sortingEnabled)
        self.addCellTypeButton.setText(QtGui.QApplication.translate("CC3DPrefs", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCellTypeButton.setText(QtGui.QApplication.translate("CC3DPrefs", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Cell Glyphs", None, QtGui.QApplication.UnicodeUTF8))
        self.cellGlyphScaleByVolumeCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "scale by volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CC3DPrefs", "Scale factor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CC3DPrefs", "Theta res", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CC3DPrefs", "Phi res", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Aditional colors", None, QtGui.QApplication.UnicodeUTF8))
        self.borderColorLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Cell border color", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterBorderColorLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Cluster border color", None, QtGui.QApplication.UnicodeUTF8))
        self.contourColorLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Contour color", None, QtGui.QApplication.UnicodeUTF8))
        self.windowColorLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Window color", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cell_type), QtGui.QApplication.translate("CC3DPrefs", "Cells/Colors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CC3DPrefs", "Field name:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Range (of magnitude for vectors)", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldMinLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldMinRangeFixedCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldMaxLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldMaxRangeFixedCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Vector Arrows", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("CC3DPrefs", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.vectorsScaleArrowCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Scale arrow length", None, QtGui.QApplication.UnicodeUTF8))
        self.vectorsArrowColorCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Fixed arrow color", None, QtGui.QApplication.UnicodeUTF8))
        self.vectorsOverlayCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Overlay Vector and Cell Field", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("CC3DPrefs", "# of labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("CC3DPrefs", "Accuracy", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldShowLegendCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Show ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Scalar Contours", None, QtGui.QApplication.UnicodeUTF8))
        self.numIsovalsInRangeLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Over range", None, QtGui.QApplication.UnicodeUTF8))
        self.isovalLabel.setText(QtGui.QApplication.translate("CC3DPrefs", "Isovalues", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_field), QtGui.QApplication.translate("CC3DPrefs", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Display Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CC3DPrefs", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CC3DPrefs", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CC3DPrefs", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CC3DPrefs", "Elevation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CC3DPrefs", "Azimuth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CC3DPrefs", "Roll", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CC3DPrefs", "Cell types invisible in 3D (example: 0,1,4)", None, QtGui.QApplication.UnicodeUTF8))
        self.boundingBoxCheckBox.setText(QtGui.QApplication.translate("CC3DPrefs", "Bounding Box Outline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CC3DPrefs", "    Color", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3D), QtGui.QApplication.translate("CC3DPrefs", "3D", None, QtGui.QApplication.UnicodeUTF8))

