# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cc3D_prefs.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CC3DPrefs(object):
    def setupUi(self, CC3DPrefs):
        CC3DPrefs.setObjectName(_fromUtf8("CC3DPrefs"))
        CC3DPrefs.resize(480, 486)
        self.verticalLayout_18 = QtGui.QVBoxLayout(CC3DPrefs)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.tabWidget = QtGui.QTabWidget(CC3DPrefs)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_output = QtGui.QWidget()
        self.tab_output.setObjectName(_fromUtf8("tab_output"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.tab_output)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.tab_output)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.updateScreenSpinBox = QtGui.QSpinBox(self.tab_output)
        self.updateScreenSpinBox.setMinimum(1)
        self.updateScreenSpinBox.setMaximum(1000000000)
        self.updateScreenSpinBox.setProperty("value", 10)
        self.updateScreenSpinBox.setObjectName(_fromUtf8("updateScreenSpinBox"))
        self.horizontalLayout_3.addWidget(self.updateScreenSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.outputImagesCheckBox = QtGui.QCheckBox(self.tab_output)
        self.outputImagesCheckBox.setObjectName(_fromUtf8("outputImagesCheckBox"))
        self.horizontalLayout_15.addWidget(self.outputImagesCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.saveImageSpinBox = QtGui.QSpinBox(self.tab_output)
        self.saveImageSpinBox.setMinimum(1)
        self.saveImageSpinBox.setMaximum(1000000000)
        self.saveImageSpinBox.setProperty("value", 100)
        self.saveImageSpinBox.setObjectName(_fromUtf8("saveImageSpinBox"))
        self.horizontalLayout_15.addWidget(self.saveImageSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_13 = QtGui.QLabel(self.tab_output)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_21.addWidget(self.label_13)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_16 = QtGui.QLabel(self.tab_output)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_22.addWidget(self.label_16)
        self.screenshot_X_SB = QtGui.QSpinBox(self.tab_output)
        self.screenshot_X_SB.setMaximum(5000)
        self.screenshot_X_SB.setProperty("value", 600)
        self.screenshot_X_SB.setObjectName(_fromUtf8("screenshot_X_SB"))
        self.horizontalLayout_22.addWidget(self.screenshot_X_SB)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_17 = QtGui.QLabel(self.tab_output)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_23.addWidget(self.label_17)
        self.screenshot_Y_SB = QtGui.QSpinBox(self.tab_output)
        self.screenshot_Y_SB.setMaximum(5000)
        self.screenshot_Y_SB.setProperty("value", 600)
        self.screenshot_Y_SB.setObjectName(_fromUtf8("screenshot_Y_SB"))
        self.horizontalLayout_23.addWidget(self.screenshot_Y_SB)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_23)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.outputLatticeDataCheckBox = QtGui.QCheckBox(self.tab_output)
        self.outputLatticeDataCheckBox.setObjectName(_fromUtf8("outputLatticeDataCheckBox"))
        self.horizontalLayout_14.addWidget(self.outputLatticeDataCheckBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.saveLatticeSpinBox = QtGui.QSpinBox(self.tab_output)
        self.saveLatticeSpinBox.setMinimum(1)
        self.saveLatticeSpinBox.setMaximum(1000000000)
        self.saveLatticeSpinBox.setProperty("value", 100)
        self.saveLatticeSpinBox.setObjectName(_fromUtf8("saveLatticeSpinBox"))
        self.horizontalLayout_14.addWidget(self.saveLatticeSpinBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16.addLayout(self.verticalLayout_9)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.line = QtGui.QFrame(self.tab_output)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_10.addWidget(self.line)
        self.debugOutputPlayerCB = QtGui.QCheckBox(self.tab_output)
        self.debugOutputPlayerCB.setObjectName(_fromUtf8("debugOutputPlayerCB"))
        self.verticalLayout_10.addWidget(self.debugOutputPlayerCB)
        self.useInternalConsoleCheckBox = QtGui.QCheckBox(self.tab_output)
        self.useInternalConsoleCheckBox.setObjectName(_fromUtf8("useInternalConsoleCheckBox"))
        self.verticalLayout_10.addWidget(self.useInternalConsoleCheckBox)
        self.closePlayerCheckBox = QtGui.QCheckBox(self.tab_output)
        self.closePlayerCheckBox.setObjectName(_fromUtf8("closePlayerCheckBox"))
        self.verticalLayout_10.addWidget(self.closePlayerCheckBox)
        self.line_2 = QtGui.QFrame(self.tab_output)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_10.addWidget(self.line_2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.projectLocationLineEdit = QtGui.QLineEdit(self.tab_output)
        self.projectLocationLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projectLocationLineEdit.setText(_fromUtf8(""))
        self.projectLocationLineEdit.setObjectName(_fromUtf8("projectLocationLineEdit"))
        self.gridLayout_6.addWidget(self.projectLocationLineEdit, 0, 0, 1, 1)
        self.projectLocationButton = QtGui.QPushButton(self.tab_output)
        self.projectLocationButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.projectLocationButton.setAutoDefault(False)
        self.projectLocationButton.setObjectName(_fromUtf8("projectLocationButton"))
        self.gridLayout_6.addWidget(self.projectLocationButton, 0, 1, 1, 3)
        self.outputLocationLineEdit = QtGui.QLineEdit(self.tab_output)
        self.outputLocationLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outputLocationLineEdit.setObjectName(_fromUtf8("outputLocationLineEdit"))
        self.gridLayout_6.addWidget(self.outputLocationLineEdit, 1, 0, 1, 1)
        self.outputLocationButton = QtGui.QPushButton(self.tab_output)
        self.outputLocationButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.outputLocationButton.setAutoDefault(False)
        self.outputLocationButton.setObjectName(_fromUtf8("outputLocationButton"))
        self.gridLayout_6.addWidget(self.outputLocationButton, 1, 1, 1, 2)
        self.outputToProjectCheckBox = QtGui.QCheckBox(self.tab_output)
        self.outputToProjectCheckBox.setObjectName(_fromUtf8("outputToProjectCheckBox"))
        self.gridLayout_6.addWidget(self.outputToProjectCheckBox, 1, 3, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.verticalLayout_21.addLayout(self.verticalLayout_10)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_output)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_25.addWidget(self.label_23)
        self.numberOfRecentSimulationsSB = QtGui.QSpinBox(self.groupBox_5)
        self.numberOfRecentSimulationsSB.setMaximum(20)
        self.numberOfRecentSimulationsSB.setProperty("value", 8)
        self.numberOfRecentSimulationsSB.setObjectName(_fromUtf8("numberOfRecentSimulationsSB"))
        self.horizontalLayout_25.addWidget(self.numberOfRecentSimulationsSB)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.floatingWindowsCB = QtGui.QCheckBox(self.groupBox_5)
        self.floatingWindowsCB.setObjectName(_fromUtf8("floatingWindowsCB"))
        self.verticalLayout_14.addWidget(self.floatingWindowsCB)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_31.addWidget(self.label_19)
        self.default_settings_PB = QtGui.QPushButton(self.groupBox_5)
        self.default_settings_PB.setObjectName(_fromUtf8("default_settings_PB"))
        self.horizontalLayout_31.addWidget(self.default_settings_PB)
        self.verticalLayout_14.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_26.addLayout(self.verticalLayout_14)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem4)
        self.verticalLayout_20.addLayout(self.horizontalLayout_26)
        self.label_19.raise_()
        self.verticalLayout_21.addWidget(self.groupBox_5)
        spacerItem5 = QtGui.QSpacerItem(20, 119, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem5)
        self.buttonBox = QtGui.QDialogButtonBox(self.tab_output)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_21.addWidget(self.buttonBox)
        self.tabWidget.addTab(self.tab_output, _fromUtf8(""))
        self.tab_cell_type = QtGui.QWidget()
        self.tab_cell_type.setObjectName(_fromUtf8("tab_cell_type"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.tab_cell_type)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_cell_type)
        self.groupBox_13.setTitle(_fromUtf8(""))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.selectCellColorLabel = QtGui.QLabel(self.groupBox_14)
        self.selectCellColorLabel.setTextFormat(QtCore.Qt.PlainText)
        self.selectCellColorLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.selectCellColorLabel.setWordWrap(True)
        self.selectCellColorLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.selectCellColorLabel.setObjectName(_fromUtf8("selectCellColorLabel"))
        self.verticalLayout_16.addWidget(self.selectCellColorLabel)
        self.typeColorTable = QtGui.QTableWidget(self.groupBox_14)
        self.typeColorTable.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeColorTable.sizePolicy().hasHeightForWidth())
        self.typeColorTable.setSizePolicy(sizePolicy)
        self.typeColorTable.setMinimumSize(QtCore.QSize(200, 0))
        self.typeColorTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.typeColorTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.typeColorTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.typeColorTable.setIconSize(QtCore.QSize(0, 0))
        self.typeColorTable.setShowGrid(True)
        self.typeColorTable.setWordWrap(False)
        self.typeColorTable.setCornerButtonEnabled(False)
        self.typeColorTable.setRowCount(20)
        self.typeColorTable.setColumnCount(3)
        self.typeColorTable.setObjectName(_fromUtf8("typeColorTable"))
        item = QtGui.QTableWidgetItem()
        self.typeColorTable.setItem(0, 1, item)
        self.typeColorTable.horizontalHeader().setVisible(False)
        self.typeColorTable.horizontalHeader().setCascadingSectionResizes(True)
        self.typeColorTable.horizontalHeader().setDefaultSectionSize(50)
        self.typeColorTable.horizontalHeader().setHighlightSections(False)
        self.typeColorTable.verticalHeader().setVisible(False)
        self.typeColorTable.verticalHeader().setDefaultSectionSize(18)
        self.typeColorTable.verticalHeader().setHighlightSections(False)
        self.typeColorTable.verticalHeader().setMinimumSectionSize(11)
        self.typeColorTable.verticalHeader().setSortIndicatorShown(True)
        self.typeColorTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_16.addWidget(self.typeColorTable)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.addCellTypeButton = QtGui.QPushButton(self.groupBox_14)
        self.addCellTypeButton.setEnabled(True)
        self.addCellTypeButton.setAutoDefault(False)
        self.addCellTypeButton.setDefault(False)
        self.addCellTypeButton.setObjectName(_fromUtf8("addCellTypeButton"))
        self.horizontalLayout_11.addWidget(self.addCellTypeButton)
        self.deleteCellTypeButton = QtGui.QPushButton(self.groupBox_14)
        self.deleteCellTypeButton.setEnabled(False)
        self.deleteCellTypeButton.setAutoDefault(False)
        self.deleteCellTypeButton.setObjectName(_fromUtf8("deleteCellTypeButton"))
        self.horizontalLayout_11.addWidget(self.deleteCellTypeButton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addWidget(self.groupBox_14)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.borderColorLabel = QtGui.QLabel(self.groupBox_11)
        self.borderColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.borderColorLabel.setObjectName(_fromUtf8("borderColorLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.borderColorLabel)
        self.cellBorderColorButton = QtGui.QToolButton(self.groupBox_11)
        self.cellBorderColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.cellBorderColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.cellBorderColorButton.setText(_fromUtf8(""))
        self.cellBorderColorButton.setObjectName(_fromUtf8("cellBorderColorButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cellBorderColorButton)
        self.clusterBorderColorLabel = QtGui.QLabel(self.groupBox_11)
        self.clusterBorderColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clusterBorderColorLabel.setObjectName(_fromUtf8("clusterBorderColorLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.clusterBorderColorLabel)
        self.clusterBorderColorButton = QtGui.QToolButton(self.groupBox_11)
        self.clusterBorderColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.clusterBorderColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.clusterBorderColorButton.setText(_fromUtf8(""))
        self.clusterBorderColorButton.setObjectName(_fromUtf8("clusterBorderColorButton"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.clusterBorderColorButton)
        self.contourColorLabel = QtGui.QLabel(self.groupBox_11)
        self.contourColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contourColorLabel.setObjectName(_fromUtf8("contourColorLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.contourColorLabel)
        self.contourColorButton = QtGui.QToolButton(self.groupBox_11)
        self.contourColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.contourColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.contourColorButton.setText(_fromUtf8(""))
        self.contourColorButton.setObjectName(_fromUtf8("contourColorButton"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.contourColorButton)
        self.windowColorLabel = QtGui.QLabel(self.groupBox_11)
        self.windowColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.windowColorLabel.setObjectName(_fromUtf8("windowColorLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.windowColorLabel)
        self.windowColorButton = QtGui.QToolButton(self.groupBox_11)
        self.windowColorButton.setEnabled(True)
        self.windowColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.windowColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.windowColorButton.setText(_fromUtf8(""))
        self.windowColorButton.setObjectName(_fromUtf8("windowColorButton"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.windowColorButton)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.windowColorSameAsMediumCB = QtGui.QCheckBox(self.groupBox_11)
        self.windowColorSameAsMediumCB.setChecked(True)
        self.windowColorSameAsMediumCB.setObjectName(_fromUtf8("windowColorSameAsMediumCB"))
        self.verticalLayout_5.addWidget(self.windowColorSameAsMediumCB)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_17.addWidget(self.groupBox_11)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.cellGlyphScaleByVolumeCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.cellGlyphScaleByVolumeCheckBox.setObjectName(_fromUtf8("cellGlyphScaleByVolumeCheckBox"))
        self.verticalLayout_11.addWidget(self.cellGlyphScaleByVolumeCheckBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.cellGlyphScale = QtGui.QLineEdit(self.groupBox_4)
        self.cellGlyphScale.setObjectName(_fromUtf8("cellGlyphScale"))
        self.gridLayout.addWidget(self.cellGlyphScale, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.cellGlyphThetaRes = QtGui.QSpinBox(self.groupBox_4)
        self.cellGlyphThetaRes.setObjectName(_fromUtf8("cellGlyphThetaRes"))
        self.gridLayout.addWidget(self.cellGlyphThetaRes, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.cellGlyphPhiRes = QtGui.QSpinBox(self.groupBox_4)
        self.cellGlyphPhiRes.setObjectName(_fromUtf8("cellGlyphPhiRes"))
        self.gridLayout.addWidget(self.cellGlyphPhiRes, 2, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_17.addWidget(self.groupBox_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout_17)
        self.horizontalLayout_24.addWidget(self.groupBox_13)
        self.tabWidget.addTab(self.tab_cell_type, _fromUtf8(""))
        self.tab_field = QtGui.QWidget()
        self.tab_field.setObjectName(_fromUtf8("tab_field"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.tab_field)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.pixelizedScalarFieldCB = QtGui.QCheckBox(self.groupBox_6)
        self.pixelizedScalarFieldCB.setObjectName(_fromUtf8("pixelizedScalarFieldCB"))
        self.verticalLayout_19.addWidget(self.pixelizedScalarFieldCB)
        self.verticalLayout_15.addWidget(self.groupBox_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.tab_field)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.fieldComboBox = QtGui.QComboBox(self.tab_field)
        self.fieldComboBox.setObjectName(_fromUtf8("fieldComboBox"))
        self.horizontalLayout_5.addWidget(self.fieldComboBox)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.showPlotAxesCB = QtGui.QCheckBox(self.tab_field)
        self.showPlotAxesCB.setObjectName(_fromUtf8("showPlotAxesCB"))
        self.horizontalLayout_6.addWidget(self.showPlotAxesCB)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.line_3 = QtGui.QFrame(self.tab_field)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_15.addWidget(self.line_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem8 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.fieldMinLabel = QtGui.QLabel(self.groupBox_8)
        self.fieldMinLabel.setObjectName(_fromUtf8("fieldMinLabel"))
        self.gridLayout_11.addWidget(self.fieldMinLabel, 0, 0, 1, 1)
        self.fieldMinRange = QtGui.QLineEdit(self.groupBox_8)
        self.fieldMinRange.setObjectName(_fromUtf8("fieldMinRange"))
        self.gridLayout_11.addWidget(self.fieldMinRange, 0, 1, 1, 1)
        self.fieldMinRangeFixedCheckBox = QtGui.QCheckBox(self.groupBox_8)
        self.fieldMinRangeFixedCheckBox.setObjectName(_fromUtf8("fieldMinRangeFixedCheckBox"))
        self.gridLayout_11.addWidget(self.fieldMinRangeFixedCheckBox, 0, 2, 1, 1)
        self.fieldMaxLabel = QtGui.QLabel(self.groupBox_8)
        self.fieldMaxLabel.setObjectName(_fromUtf8("fieldMaxLabel"))
        self.gridLayout_11.addWidget(self.fieldMaxLabel, 1, 0, 1, 1)
        self.fieldMaxRange = QtGui.QLineEdit(self.groupBox_8)
        self.fieldMaxRange.setObjectName(_fromUtf8("fieldMaxRange"))
        self.gridLayout_11.addWidget(self.fieldMaxRange, 1, 1, 1, 1)
        self.fieldMaxRangeFixedCheckBox = QtGui.QCheckBox(self.groupBox_8)
        self.fieldMaxRangeFixedCheckBox.setObjectName(_fromUtf8("fieldMaxRangeFixedCheckBox"))
        self.gridLayout_11.addWidget(self.fieldMaxRangeFixedCheckBox, 1, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_11)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        self.label_18.setMinimumSize(QtCore.QSize(0, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_20.addWidget(self.label_18)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.vectorsArrowLength = QtGui.QSpinBox(self.groupBox_9)
        self.vectorsArrowLength.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsArrowLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vectorsArrowLength.setMaximum(9999)
        self.vectorsArrowLength.setObjectName(_fromUtf8("vectorsArrowLength"))
        self.horizontalLayout_20.addWidget(self.vectorsArrowLength)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.vectorsScaleArrowCheckBox = QtGui.QCheckBox(self.groupBox_9)
        self.vectorsScaleArrowCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsScaleArrowCheckBox.setObjectName(_fromUtf8("vectorsScaleArrowCheckBox"))
        self.horizontalLayout_19.addWidget(self.vectorsScaleArrowCheckBox)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.vectorsArrowColorCheckBox = QtGui.QCheckBox(self.groupBox_9)
        self.vectorsArrowColorCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsArrowColorCheckBox.setObjectName(_fromUtf8("vectorsArrowColorCheckBox"))
        self.horizontalLayout_18.addWidget(self.vectorsArrowColorCheckBox)
        self.vectorsArrowColorButton = QtGui.QToolButton(self.groupBox_9)
        self.vectorsArrowColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.vectorsArrowColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.vectorsArrowColorButton.setText(_fromUtf8(""))
        self.vectorsArrowColorButton.setObjectName(_fromUtf8("vectorsArrowColorButton"))
        self.horizontalLayout_18.addWidget(self.vectorsArrowColorButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.vectorsOverlayCheckBox = QtGui.QCheckBox(self.tab_field)
        self.vectorsOverlayCheckBox.setObjectName(_fromUtf8("vectorsOverlayCheckBox"))
        self.verticalLayout_2.addWidget(self.vectorsOverlayCheckBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.fieldLegendNumLabels = QtGui.QSpinBox(self.groupBox_7)
        self.fieldLegendNumLabels.setMinimumSize(QtCore.QSize(0, 30))
        self.fieldLegendNumLabels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fieldLegendNumLabels.setMaximum(9999)
        self.fieldLegendNumLabels.setObjectName(_fromUtf8("fieldLegendNumLabels"))
        self.horizontalLayout_7.addWidget(self.fieldLegendNumLabels)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.fieldLegendAccuracy = QtGui.QSpinBox(self.groupBox_7)
        self.fieldLegendAccuracy.setMinimumSize(QtCore.QSize(0, 30))
        self.fieldLegendAccuracy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fieldLegendAccuracy.setMaximum(9999)
        self.fieldLegendAccuracy.setObjectName(_fromUtf8("fieldLegendAccuracy"))
        self.horizontalLayout_8.addWidget(self.fieldLegendAccuracy)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.fieldShowLegendCheckBox = QtGui.QCheckBox(self.groupBox_7)
        self.fieldShowLegendCheckBox.setObjectName(_fromUtf8("fieldShowLegendCheckBox"))
        self.horizontalLayout_9.addWidget(self.fieldShowLegendCheckBox)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.gridLayout_7.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_field)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.numIsovalsInRangeLabel = QtGui.QLabel(self.groupBox_12)
        self.numIsovalsInRangeLabel.setObjectName(_fromUtf8("numIsovalsInRangeLabel"))
        self.gridLayout_10.addWidget(self.numIsovalsInRangeLabel, 2, 0, 1, 1)
        self.numberOfContoursLinesSpinBox = QtGui.QSpinBox(self.groupBox_12)
        self.numberOfContoursLinesSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfContoursLinesSpinBox.setMaximum(9999)
        self.numberOfContoursLinesSpinBox.setObjectName(_fromUtf8("numberOfContoursLinesSpinBox"))
        self.gridLayout_10.addWidget(self.numberOfContoursLinesSpinBox, 2, 1, 1, 1)
        self.isovalList = QtGui.QLineEdit(self.groupBox_12)
        self.isovalList.setObjectName(_fromUtf8("isovalList"))
        self.gridLayout_10.addWidget(self.isovalList, 1, 1, 1, 1)
        self.isovalLabel = QtGui.QLabel(self.groupBox_12)
        self.isovalLabel.setObjectName(_fromUtf8("isovalLabel"))
        self.gridLayout_10.addWidget(self.isovalLabel, 1, 0, 1, 1)
        self.contoursShowCB = QtGui.QCheckBox(self.groupBox_12)
        self.contoursShowCB.setObjectName(_fromUtf8("contoursShowCB"))
        self.gridLayout_10.addWidget(self.contoursShowCB, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_28.addLayout(self.verticalLayout_15)
        self.tabWidget.addTab(self.tab_field, _fromUtf8(""))
        self.tab_3D = QtGui.QWidget()
        self.tab_3D.setObjectName(_fromUtf8("tab_3D"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.tab_3D)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem14 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.groupBox = QtGui.QGroupBox(self.tab_3D)
        self.groupBox.setEnabled(False)
        self.groupBox.setMinimumSize(QtCore.QSize(110, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 91, 112))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(25, 30))
        self.spinBox.setSpecialValueText(_fromUtf8(""))
        self.spinBox.setMaximum(999)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_5.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_2.setMaximum(999)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_5.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_3.setMaximum(999)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_5.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem15 = QtGui.QSpacerItem(13, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3D)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_6.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_6.setSpecialValueText(_fromUtf8(""))
        self.spinBox_6.setMaximum(999)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_3.addWidget(self.spinBox_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_7.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_7.setMaximum(999)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_3.addWidget(self.spinBox_7, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_8.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_8.setMaximum(999)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout_3.addWidget(self.spinBox_8, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        spacerItem16 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3D)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(2, 1, 2, 1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cellTypesInvisibleList = QtGui.QLineEdit(self.groupBox_2)
        self.cellTypesInvisibleList.setObjectName(_fromUtf8("cellTypesInvisibleList"))
        self.horizontalLayout.addWidget(self.cellTypesInvisibleList)
        self.verticalLayout_22.addWidget(self.groupBox_2)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_27.addLayout(self.verticalLayout_4)
        spacerItem17 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem17)
        self.verticalLayout_22.addLayout(self.horizontalLayout_27)
        spacerItem18 = QtGui.QSpacerItem(20, 103, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem18)
        self.tabWidget.addTab(self.tab_3D, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.boundingBoxCheckBox = QtGui.QCheckBox(self.groupBox_10)
        self.boundingBoxCheckBox.setObjectName(_fromUtf8("boundingBoxCheckBox"))
        self.horizontalLayout_29.addWidget(self.boundingBoxCheckBox)
        spacerItem19 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem19)
        self.label_12 = QtGui.QLabel(self.groupBox_10)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_29.addWidget(self.label_12)
        self.boundingBoxColorButton = QtGui.QToolButton(self.groupBox_10)
        self.boundingBoxColorButton.setEnabled(True)
        self.boundingBoxColorButton.setText(_fromUtf8(""))
        self.boundingBoxColorButton.setObjectName(_fromUtf8("boundingBoxColorButton"))
        self.horizontalLayout_29.addWidget(self.boundingBoxColorButton)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.verticalLayout_24.addWidget(self.groupBox_10)
        self.groupBox_15 = QtGui.QGroupBox(self.tab)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.showAxesCB = QtGui.QCheckBox(self.groupBox_15)
        self.showAxesCB.setObjectName(_fromUtf8("showAxesCB"))
        self.horizontalLayout_30.addWidget(self.showAxesCB)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem20)
        self.label_21 = QtGui.QLabel(self.groupBox_15)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_30.addWidget(self.label_21)
        self.axesColorButton = QtGui.QToolButton(self.groupBox_15)
        self.axesColorButton.setEnabled(True)
        self.axesColorButton.setText(_fromUtf8(""))
        self.axesColorButton.setObjectName(_fromUtf8("axesColorButton"))
        self.horizontalLayout_30.addWidget(self.axesColorButton)
        self.verticalLayout_23.addLayout(self.horizontalLayout_30)
        self.showHorizontalAxesLabelsCB = QtGui.QCheckBox(self.groupBox_15)
        self.showHorizontalAxesLabelsCB.setObjectName(_fromUtf8("showHorizontalAxesLabelsCB"))
        self.verticalLayout_23.addWidget(self.showHorizontalAxesLabelsCB)
        self.showVerticalAxesLabelsCB = QtGui.QCheckBox(self.groupBox_15)
        self.showVerticalAxesLabelsCB.setObjectName(_fromUtf8("showVerticalAxesLabelsCB"))
        self.verticalLayout_23.addWidget(self.showVerticalAxesLabelsCB)
        self.verticalLayout_24.addWidget(self.groupBox_15)
        self.gridLayout_2.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(201, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 0, 1, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 172, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem22, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_18.addWidget(self.tabWidget)

        self.retranslateUi(CC3DPrefs)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CC3DPrefs.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CC3DPrefs.reject)
        QtCore.QObject.connect(self.contoursShowCB, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.isovalList.setEnabled)
        QtCore.QObject.connect(self.contoursShowCB, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.numberOfContoursLinesSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CC3DPrefs)

    def retranslateUi(self, CC3DPrefs):
        CC3DPrefs.setWindowTitle(_translate("CC3DPrefs", "CC3D Preferences", None))
        self.tabWidget.setToolTip(_translate("CC3DPrefs", "When checked uses floating window layout instead of Multi Document Interface", None))
        self.label_5.setText(_translate("CC3DPrefs", "Update screen every Nth MCS", None))
        self.outputImagesCheckBox.setText(_translate("CC3DPrefs", "Save image every Nth MCS", None))
        self.label_13.setText(_translate("CC3DPrefs", "Screenshot Resolution     ", None))
        self.label_16.setText(_translate("CC3DPrefs", "X", None))
        self.label_17.setText(_translate("CC3DPrefs", "Y", None))
        self.outputLatticeDataCheckBox.setText(_translate("CC3DPrefs", "Save lattice every Nth MCS", None))
        self.debugOutputPlayerCB.setText(_translate("CC3DPrefs", "Turn On Player Debug Output", None))
        self.useInternalConsoleCheckBox.setText(_translate("CC3DPrefs", "Use internal console for text output", None))
        self.closePlayerCheckBox.setText(_translate("CC3DPrefs", "Close Player after simulation ends", None))
        self.projectLocationButton.setText(_translate("CC3DPrefs", "Project Location", None))
        self.outputLocationButton.setText(_translate("CC3DPrefs", "Output", None))
        self.outputToProjectCheckBox.setText(_translate("CC3DPrefs", "=Project", None))
        self.groupBox_5.setTitle(_translate("CC3DPrefs", "Miscellaneous", None))
        self.label_23.setText(_translate("CC3DPrefs", "Number of recent simulations", None))
        self.floatingWindowsCB.setToolTip(_translate("CC3DPrefs", "Checking it switches from Multi Document interface to flowting windows one. The change will take place after Player restart", None))
        self.floatingWindowsCB.setText(_translate("CC3DPrefs", "Use Floating Windows", None))
        self.label_19.setText(_translate("CC3DPrefs", "Restore Default Settings", None))
        self.default_settings_PB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Restores default Player setting. This is useful when you determine that settings file is causeing PLayer to crash</p></body></html>", None))
        self.default_settings_PB.setText(_translate("CC3DPrefs", "Default Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_output), _translate("CC3DPrefs", "Output", None))
        self.groupBox_14.setTitle(_translate("CC3DPrefs", "Cell Types and Colors", None))
        self.selectCellColorLabel.setText(_translate("CC3DPrefs", "Select a row in the table to change that cell type color.   Type        Name           Color", None))
        __sortingEnabled = self.typeColorTable.isSortingEnabled()
        self.typeColorTable.setSortingEnabled(False)
        self.typeColorTable.setSortingEnabled(__sortingEnabled)
        self.addCellTypeButton.setText(_translate("CC3DPrefs", "Add", None))
        self.deleteCellTypeButton.setText(_translate("CC3DPrefs", "-", None))
        self.groupBox_11.setTitle(_translate("CC3DPrefs", "Aditional colors", None))
        self.borderColorLabel.setText(_translate("CC3DPrefs", "Cell border color", None))
        self.clusterBorderColorLabel.setText(_translate("CC3DPrefs", "Cluster border color", None))
        self.contourColorLabel.setText(_translate("CC3DPrefs", "Contour color", None))
        self.windowColorLabel.setText(_translate("CC3DPrefs", "Window color", None))
        self.windowColorSameAsMediumCB.setText(_translate("CC3DPrefs", "Window color same as Medium", None))
        self.groupBox_4.setTitle(_translate("CC3DPrefs", "Cell Glyphs", None))
        self.cellGlyphScaleByVolumeCheckBox.setText(_translate("CC3DPrefs", "scale by volume", None))
        self.label_9.setText(_translate("CC3DPrefs", "Scale factor", None))
        self.label_10.setText(_translate("CC3DPrefs", "Theta res", None))
        self.label_11.setText(_translate("CC3DPrefs", "Phi res", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cell_type), _translate("CC3DPrefs", "Cells/Colors", None))
        self.groupBox_6.setTitle(_translate("CC3DPrefs", "General properties", None))
        self.pixelizedScalarFieldCB.setToolTip(_translate("CC3DPrefs", "Checking this box will cause cartesian concentration field in 2D be drawn using explicit pixels providing \"exact\" representation of the field. Unchecked box will mean that field will be smoothed. ", None))
        self.pixelizedScalarFieldCB.setText(_translate("CC3DPrefs", "Pixelized scalar plot (\"exact\")", None))
        self.label_6.setText(_translate("CC3DPrefs", "Field name:", None))
        self.showPlotAxesCB.setText(_translate("CC3DPrefs", "Show Axes", None))
        self.groupBox_8.setTitle(_translate("CC3DPrefs", "Range (of magnitude for vectors)", None))
        self.fieldMinLabel.setText(_translate("CC3DPrefs", "Min", None))
        self.fieldMinRangeFixedCheckBox.setText(_translate("CC3DPrefs", "Fixed", None))
        self.fieldMaxLabel.setText(_translate("CC3DPrefs", "Max", None))
        self.fieldMaxRangeFixedCheckBox.setText(_translate("CC3DPrefs", "Fixed", None))
        self.groupBox_9.setTitle(_translate("CC3DPrefs", "Vector Arrows", None))
        self.label_18.setText(_translate("CC3DPrefs", "Length", None))
        self.vectorsScaleArrowCheckBox.setText(_translate("CC3DPrefs", "Scale arrow length", None))
        self.vectorsArrowColorCheckBox.setText(_translate("CC3DPrefs", "Fixed arrow color", None))
        self.vectorsOverlayCheckBox.setText(_translate("CC3DPrefs", "Overlay Vector and Cell Field", None))
        self.groupBox_7.setTitle(_translate("CC3DPrefs", "Legend", None))
        self.label_14.setText(_translate("CC3DPrefs", "# of labels", None))
        self.label_15.setText(_translate("CC3DPrefs", "Accuracy", None))
        self.fieldShowLegendCheckBox.setText(_translate("CC3DPrefs", "Show ", None))
        self.groupBox_12.setTitle(_translate("CC3DPrefs", "Scalar Contours", None))
        self.numIsovalsInRangeLabel.setText(_translate("CC3DPrefs", "Over range", None))
        self.isovalLabel.setText(_translate("CC3DPrefs", "Isovalues", None))
        self.contoursShowCB.setText(_translate("CC3DPrefs", "Show", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_field), _translate("CC3DPrefs", "Field", None))
        self.groupBox.setTitle(_translate("CC3DPrefs", "Display Size", None))
        self.label.setText(_translate("CC3DPrefs", "X", None))
        self.label_2.setText(_translate("CC3DPrefs", "Y", None))
        self.label_3.setText(_translate("CC3DPrefs", "Z", None))
        self.groupBox_3.setTitle(_translate("CC3DPrefs", "Camera", None))
        self.label_4.setText(_translate("CC3DPrefs", "Elevation", None))
        self.label_7.setText(_translate("CC3DPrefs", "Azimuth", None))
        self.label_8.setText(_translate("CC3DPrefs", "Roll", None))
        self.groupBox_2.setTitle(_translate("CC3DPrefs", "Cell types invisible in 3D (example: 0,1,4)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3D), _translate("CC3DPrefs", "3D", None))
        self.groupBox_10.setTitle(_translate("CC3DPrefs", "Bounding Box", None))
        self.boundingBoxCheckBox.setText(_translate("CC3DPrefs", "Bounding Box Outline", None))
        self.label_12.setText(_translate("CC3DPrefs", "    Color", None))
        self.groupBox_15.setTitle(_translate("CC3DPrefs", "Axes", None))
        self.showAxesCB.setText(_translate("CC3DPrefs", "Show Axes", None))
        self.label_21.setText(_translate("CC3DPrefs", "    Color", None))
        self.showHorizontalAxesLabelsCB.setText(_translate("CC3DPrefs", "Show Horizontal Axes Labels (2D)", None))
        self.showVerticalAxesLabelsCB.setText(_translate("CC3DPrefs", "Show Vertical Axes Labels (2D)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CC3DPrefs", "Axes\'n\'Decor", None))

