#include "BiasVectorSteppable.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto biasVectorSteppableProxy = registerPlugin<Steppable, BiasVectorSteppable>(
	"BiasVectorSteppable", 
	"Autogenerated steppeble - the author of the plugin should provide brief description here",
	&Simulator::steppableManager
);
