        
#include "ClusterSurfacePlugin.h"

#include <CompuCell3D/Simulator.h>
using namespace CompuCell3D;

#include <BasicUtils/BasicPluginProxy.h>

BasicPluginProxy<Plugin, ClusterSurfacePlugin>
clusterSurfaceProxy("ClusterSurface", "Autogenerated plugin - the author of the plugin should provide brief description here",
         &Simulator::pluginManager);
