#include "ClusterSurfacePlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto clusterSurfaceProxy = registerPlugin<Plugin, ClusterSurfacePlugin>(
        "ClusterSurface",
        "Autogenerated plugin - the author of the plugin should provide brief description here",
        &Simulator::pluginManager
);
