# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameter_scan_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParamScanDialog(object):
    def setupUi(self, ParamScanDialog):
        ParamScanDialog.setObjectName("ParamScanDialog")
        ParamScanDialog.resize(869, 371)
        self.verticalLayout = QtWidgets.QVBoxLayout(ParamScanDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ParamScanDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.param_scan_simulation_LE = QtWidgets.QLineEdit(ParamScanDialog)
        self.param_scan_simulation_LE.setObjectName("param_scan_simulation_LE")
        self.gridLayout.addWidget(self.param_scan_simulation_LE, 0, 1, 1, 1)
        self.browse_simulation_PB = QtWidgets.QPushButton(ParamScanDialog)
        self.browse_simulation_PB.setObjectName("browse_simulation_PB")
        self.gridLayout.addWidget(self.browse_simulation_PB, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(ParamScanDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.output_dir_LE = QtWidgets.QLineEdit(ParamScanDialog)
        self.output_dir_LE.setObjectName("output_dir_LE")
        self.gridLayout.addWidget(self.output_dir_LE, 1, 1, 1, 1)
        self.browse_output_dir_PB = QtWidgets.QPushButton(ParamScanDialog)
        self.browse_output_dir_PB.setObjectName("browse_output_dir_PB")
        self.gridLayout.addWidget(self.browse_output_dir_PB, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(ParamScanDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.output_freq_SB = QtWidgets.QSpinBox(ParamScanDialog)
        self.output_freq_SB.setMaximum(100000000)
        self.output_freq_SB.setProperty("value", 100)
        self.output_freq_SB.setObjectName("output_freq_SB")
        self.gridLayout.addWidget(self.output_freq_SB, 2, 1, 1, 1)
        self.output_snapshot_CB = QtWidgets.QCheckBox(ParamScanDialog)
        self.output_snapshot_CB.setChecked(True)
        self.output_snapshot_CB.setObjectName("output_snapshot_CB")
        self.gridLayout.addWidget(self.output_snapshot_CB, 2, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(ParamScanDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.screenshot_freq_CB = QtWidgets.QSpinBox(ParamScanDialog)
        self.screenshot_freq_CB.setMaximum(1000000000)
        self.screenshot_freq_CB.setProperty("value", 100)
        self.screenshot_freq_CB.setObjectName("screenshot_freq_CB")
        self.gridLayout.addWidget(self.screenshot_freq_CB, 3, 1, 1, 1)
        self.output_screenshot_CB = QtWidgets.QCheckBox(ParamScanDialog)
        self.output_screenshot_CB.setChecked(True)
        self.output_screenshot_CB.setObjectName("output_screenshot_CB")
        self.gridLayout.addWidget(self.output_screenshot_CB, 3, 2, 1, 2)
        self.gui_CB = QtWidgets.QCheckBox(ParamScanDialog)
        self.gui_CB.setObjectName("gui_CB")
        self.gridLayout.addWidget(self.gui_CB, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(ParamScanDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.install_dir_LE = QtWidgets.QLineEdit(ParamScanDialog)
        self.install_dir_LE.setObjectName("install_dir_LE")
        self.gridLayout.addWidget(self.install_dir_LE, 5, 1, 1, 1)
        self.install_dir_browse_PB = QtWidgets.QPushButton(ParamScanDialog)
        self.install_dir_browse_PB.setObjectName("install_dir_browse_PB")
        self.gridLayout.addWidget(self.install_dir_browse_PB, 5, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(ParamScanDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.update_cml_PB = QtWidgets.QPushButton(ParamScanDialog)
        self.update_cml_PB.setObjectName("update_cml_PB")
        self.horizontalLayout_2.addWidget(self.update_cml_PB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.cml_PTE = QtWidgets.QPlainTextEdit(ParamScanDialog)
        self.cml_PTE.setReadOnly(True)
        self.cml_PTE.setObjectName("cml_PTE")
        self.verticalLayout.addWidget(self.cml_PTE)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancel_PB = QtWidgets.QPushButton(ParamScanDialog)
        self.cancel_PB.setObjectName("cancel_PB")
        self.horizontalLayout.addWidget(self.cancel_PB)
        self.run_PB = QtWidgets.QPushButton(ParamScanDialog)
        self.run_PB.setObjectName("run_PB")
        self.horizontalLayout.addWidget(self.run_PB)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ParamScanDialog)
        self.cancel_PB.clicked.connect(ParamScanDialog.reject)
        self.run_PB.clicked.connect(ParamScanDialog.accept)
        self.output_snapshot_CB.toggled['bool'].connect(self.output_freq_SB.setEnabled)
        self.output_screenshot_CB.toggled['bool'].connect(self.screenshot_freq_CB.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ParamScanDialog)

    def retranslateUi(self, ParamScanDialog):
        _translate = QtCore.QCoreApplication.translate
        ParamScanDialog.setWindowTitle(_translate("ParamScanDialog", "Parameter Scan Launcher"))
        self.label.setText(_translate("ParamScanDialog", "Param Scan Simulation"))
        self.param_scan_simulation_LE.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>abs path to .cc3d project that has parameter scan definitions in it</p></body></html>"))
        self.browse_simulation_PB.setText(_translate("ParamScanDialog", "Browse..."))
        self.label_2.setText(_translate("ParamScanDialog", "Output Dir"))
        self.output_dir_LE.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>output folder for parameter scans</p></body></html>"))
        self.browse_output_dir_PB.setText(_translate("ParamScanDialog", "Browse..."))
        self.label_3.setText(_translate("ParamScanDialog", "Snapshot Output Frequency"))
        self.output_freq_SB.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>visualization snapshots output frequency</p></body></html>"))
        self.output_snapshot_CB.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>enables storing of visualization snapshots</p></body></html>"))
        self.output_snapshot_CB.setText(_translate("ParamScanDialog", "Output Snapshots"))
        self.label_4.setText(_translate("ParamScanDialog", "Screenshot Output Frequency"))
        self.screenshot_freq_CB.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>screenshot output frequency</p></body></html>"))
        self.output_screenshot_CB.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>enables outputting of screenshots</p></body></html>"))
        self.output_screenshot_CB.setText(_translate("ParamScanDialog", "Output Screenshots"))
        self.gui_CB.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>Enables use of GUI for parameter Scan. GUI-less parameter scans often run faster so unless you really want to see livbe output of the parameter scan we suggest you leave this box unchecked</p></body></html>"))
        self.gui_CB.setText(_translate("ParamScanDialog", "Use GUI"))
        self.label_5.setText(_translate("ParamScanDialog", "CC3D Installation dir"))
        self.install_dir_LE.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>Absolute path to the folder where cc3d run scripts are installed (i.e. cc3d installation folder)</p></body></html>"))
        self.install_dir_browse_PB.setText(_translate("ParamScanDialog", "Browse ..."))
        self.label_6.setText(_translate("ParamScanDialog", "Command Line"))
        self.update_cml_PB.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>Displays command line that will be executed to run parameter scans. This is useful when you want to run parameter scan from a separate console. Simply copy the command line text and past int he console windowd and run</p></body></html>"))
        self.update_cml_PB.setText(_translate("ParamScanDialog", "Display Command Line"))
        self.cancel_PB.setText(_translate("ParamScanDialog", "Cancel"))
        self.run_PB.setToolTip(_translate("ParamScanDialog", "<html><head/><body><p>Runs parameter Scan. KEep in mind that it is often more useful to copy command line of the parameter scan and run it in the separate console</p></body></html>"))
        self.run_PB.setText(_translate("ParamScanDialog", "Run"))
