CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk # [osx]

c_compiler:
  - vs2019 # [win]
  - gcc # [linux]
  - clang # [osx]

cxx_compiler: 
  - vs2019 # [win]
  - gxx # [linux]
  - clangxx # [osx]

python:
  - 3.7
  # - 3.8

openmp:
  - llvm-openmp # [osx]


pin_run_as_build:
  python: x.x


# conda install llvm-openmp - to get openmp on OSX