CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk # [osx]

c_compiler: 
  - vs2015 # [win]
  - gcc # [linux]
  - clang # [osx]

cxx_compiler: 
  - vs2015 # [win]
  - gxx # [linux]
  - clangxx # [osx]

python:
  - 3.7
  # - 3.8

pin_run_as_build:
  python: x.x
