# when building as standalone package uncomment line below and set version and build_number to proper values
{% set version = "4.5.0" %}
{% set build_number = "0" %}

#{% set version = "4.3.0" %}
#{% set build_number = "16" %}

package:
  name: cc3d
  version: {{ version }}

about:
  home: https://compucell3d.org
  license: MIT
  license_file: ../CompuCell3D/License.txt
  summary: Multiscale multicellular virtual tissue modeling and simulation environment

extra:
  maintainers: T.J. Sego, Maciek Swat

source:
  # url: https://github.com/CompuCell3D/CompuCell3D/archive/master.tar.gz
  path: ../

build:
  number: {{ build_number }}
  ignore_run_exports:
    # Mitigating hard dependency on tbb by tbb-devel
    - tbb

requirements:
  host:
    - python {{ python }}
    - numpy=1.21
    - vtk=9.2
    - eigen
    - tbb-devel=2021
    - boost=1.78
    - cmake>=3.14
    - swig=3
    - psutil
    - deprecated
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ openmp }} # [osx]

  build:
    - cmake>=3.14
    - swig=3
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ openmp }} # [osx]

  run:
    - python {{ python }}
    - numpy=1.21
    - vtk=9.2
    - eigen
    - tbb-devel=2021
    - boost=1.78
    - cmake>=3.14
    - swig=3
    - psutil
    - deprecated
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ openmp }} # [osx]


  run_constrained:
    - tbb=2021

# on windows we can run conda
#  build . -c conda-forge -c compucell3d to force conda to use
#  specified channels as sources of packages
