package:
  name: cc3d
  version: 4.3.0

about:
  home: https://compucell3d.org
  license: GPL
  summary: Multiscale multicellular virtual tissue modeling and simulation environment

extra:
  maintainers: T.J. Sego, Maciek Swat

source:
  # url: https://github.com/CompuCell3D/CompuCell3D/archive/master.tar.gz
  path: ../

build:
  number: 3
  ignore_run_exports:
    # Mitigating hard dependency on tbb by tbb-devel
    - tbb

requirements:
  host:
    - python {{ python }}
    - numpy=1.18
    - vtk=8.2
    - eigen
    - tbb-devel=2020
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ openmp }}

  build:
    - cmake>=3.14
    - swig=3
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ openmp }}

  run:
    - python
    - numpy=1.18
    - vtk=8.2
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('vtk') }}
    - scipy
    - pandas
    - jinja2
    - deprecated
    - psutil
    - cc3dext_maboss

#  run:
#    - python
#    - numpy=1.18
#    - vtk=8.2
#    - {{ pin_compatible('numpy') }}
#    - {{ pin_compatible('vtk') }}
#    - scipy
#    - pandas
#    - jinja2=3.0.2
#    - deprecated=1.2.12
#    - psutil=5.8.0
#    - cc3dext_maboss

  run_constrained:
    - tbb=2020
