# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cc3D_prefs.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CC3DPrefs(object):
    def setupUi(self, CC3DPrefs):
        CC3DPrefs.setObjectName("CC3DPrefs")
        CC3DPrefs.resize(634, 517)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(CC3DPrefs)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidget = QtWidgets.QTabWidget(CC3DPrefs)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_output)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_output)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_17)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.updateScreenSpinBox = QtWidgets.QSpinBox(self.groupBox_17)
        self.updateScreenSpinBox.setMinimum(1)
        self.updateScreenSpinBox.setMaximum(1000000000)
        self.updateScreenSpinBox.setProperty("value", 10)
        self.updateScreenSpinBox.setObjectName("updateScreenSpinBox")
        self.horizontalLayout_3.addWidget(self.updateScreenSpinBox)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.outputImagesCheckBox = QtWidgets.QCheckBox(self.groupBox_17)
        self.outputImagesCheckBox.setObjectName("outputImagesCheckBox")
        self.horizontalLayout_15.addWidget(self.outputImagesCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.saveImageSpinBox = QtWidgets.QSpinBox(self.groupBox_17)
        self.saveImageSpinBox.setMinimum(1)
        self.saveImageSpinBox.setMaximum(1000000000)
        self.saveImageSpinBox.setProperty("value", 100)
        self.saveImageSpinBox.setObjectName("saveImageSpinBox")
        self.horizontalLayout_15.addWidget(self.saveImageSpinBox)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_15)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.groupBox_17)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_16 = QtWidgets.QLabel(self.groupBox_17)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_22.addWidget(self.label_16)
        self.screenshot_X_SB = QtWidgets.QSpinBox(self.groupBox_17)
        self.screenshot_X_SB.setMaximum(5000)
        self.screenshot_X_SB.setProperty("value", 600)
        self.screenshot_X_SB.setObjectName("screenshot_X_SB")
        self.horizontalLayout_22.addWidget(self.screenshot_X_SB)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(self.groupBox_17)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.screenshot_Y_SB = QtWidgets.QSpinBox(self.groupBox_17)
        self.screenshot_Y_SB.setMaximum(5000)
        self.screenshot_Y_SB.setProperty("value", 600)
        self.screenshot_Y_SB.setObjectName("screenshot_Y_SB")
        self.horizontalLayout_23.addWidget(self.screenshot_Y_SB)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_17)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.outputLatticeDataCheckBox = QtWidgets.QCheckBox(self.groupBox_17)
        self.outputLatticeDataCheckBox.setObjectName("outputLatticeDataCheckBox")
        self.horizontalLayout_21.addWidget(self.outputLatticeDataCheckBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.saveLatticeSpinBox = QtWidgets.QSpinBox(self.groupBox_17)
        self.saveLatticeSpinBox.setMinimum(1)
        self.saveLatticeSpinBox.setMaximum(1000000000)
        self.saveLatticeSpinBox.setProperty("value", 100)
        self.saveLatticeSpinBox.setObjectName("saveLatticeSpinBox")
        self.horizontalLayout_21.addWidget(self.saveLatticeSpinBox)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_21)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_33)
        self.verticalLayout_19.addLayout(self.verticalLayout_10)
        self.line_2 = QtWidgets.QFrame(self.groupBox_17)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_19.addWidget(self.line_2)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_19 = QtWidgets.QLabel(self.groupBox_17)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_34.addWidget(self.label_19)
        self.outputLocationLineEdit = QtWidgets.QLineEdit(self.groupBox_17)
        self.outputLocationLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outputLocationLineEdit.setObjectName("outputLocationLineEdit")
        self.horizontalLayout_34.addWidget(self.outputLocationLineEdit)
        self.outputLocationButton = QtWidgets.QPushButton(self.groupBox_17)
        self.outputLocationButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.outputLocationButton.setAutoDefault(False)
        self.outputLocationButton.setObjectName("outputLocationButton")
        self.horizontalLayout_34.addWidget(self.outputLocationButton)
        self.outputToProjectCheckBox = QtWidgets.QCheckBox(self.groupBox_17)
        self.outputToProjectCheckBox.setObjectName("outputToProjectCheckBox")
        self.horizontalLayout_34.addWidget(self.outputToProjectCheckBox)
        self.verticalLayout_19.addLayout(self.horizontalLayout_34)
        self.line = QtWidgets.QFrame(self.groupBox_17)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_19.addWidget(self.line)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.debugOutputPlayerCB = QtWidgets.QCheckBox(self.groupBox_17)
        self.debugOutputPlayerCB.setObjectName("debugOutputPlayerCB")
        self.verticalLayout_14.addWidget(self.debugOutputPlayerCB)
        self.useInternalConsoleCheckBox = QtWidgets.QCheckBox(self.groupBox_17)
        self.useInternalConsoleCheckBox.setObjectName("useInternalConsoleCheckBox")
        self.verticalLayout_14.addWidget(self.useInternalConsoleCheckBox)
        self.closePlayerCheckBox = QtWidgets.QCheckBox(self.groupBox_17)
        self.closePlayerCheckBox.setObjectName("closePlayerCheckBox")
        self.verticalLayout_14.addWidget(self.closePlayerCheckBox)
        self.verticalLayout_19.addLayout(self.verticalLayout_14)
        self.verticalLayout_25.addWidget(self.groupBox_17)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_output)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.restart_CB = QtWidgets.QCheckBox(self.groupBox_16)
        self.restart_CB.setObjectName("restart_CB")
        self.gridLayout_4.addWidget(self.restart_CB, 0, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_16)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 3, 1, 1)
        self.restart_freq_SB = QtWidgets.QSpinBox(self.groupBox_16)
        self.restart_freq_SB.setEnabled(False)
        self.restart_freq_SB.setMaximum(1000000000)
        self.restart_freq_SB.setProperty("value", 100)
        self.restart_freq_SB.setObjectName("restart_freq_SB")
        self.gridLayout_4.addWidget(self.restart_freq_SB, 0, 4, 1, 1)
        self.multiple_restart_snapshots_CB = QtWidgets.QCheckBox(self.groupBox_16)
        self.multiple_restart_snapshots_CB.setEnabled(False)
        self.multiple_restart_snapshots_CB.setObjectName("multiple_restart_snapshots_CB")
        self.gridLayout_4.addWidget(self.multiple_restart_snapshots_CB, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 1, 1, 2)
        self.verticalLayout_25.addWidget(self.groupBox_16)
        spacerItem9 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem9)
        self.tabWidget.addTab(self.tab_output, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 0, 1, 1)
        self.floatingWindowsCB = QtWidgets.QCheckBox(self.groupBox_5)
        self.floatingWindowsCB.setObjectName("floatingWindowsCB")
        self.gridLayout_6.addWidget(self.floatingWindowsCB, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 2, 0, 1, 2)
        self.numberOfStepOutputsSB = QtWidgets.QSpinBox(self.groupBox_5)
        self.numberOfStepOutputsSB.setMaximum(1000)
        self.numberOfStepOutputsSB.setProperty("value", 10)
        self.numberOfStepOutputsSB.setObjectName("numberOfStepOutputsSB")
        self.gridLayout_6.addWidget(self.numberOfStepOutputsSB, 2, 2, 1, 1)
        self.numberOfRecentSimulationsSB = QtWidgets.QSpinBox(self.groupBox_5)
        self.numberOfRecentSimulationsSB.setMaximum(20)
        self.numberOfRecentSimulationsSB.setProperty("value", 8)
        self.numberOfRecentSimulationsSB.setObjectName("numberOfRecentSimulationsSB")
        self.gridLayout_6.addWidget(self.numberOfRecentSimulationsSB, 0, 2, 1, 1)
        self.horizontalLayout_25.addLayout(self.gridLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.verticalLayout_20.addWidget(self.groupBox_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.projectLocationLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.projectLocationLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projectLocationLineEdit.setText("")
        self.projectLocationLineEdit.setObjectName("projectLocationLineEdit")
        self.horizontalLayout_14.addWidget(self.projectLocationLineEdit)
        self.projectLocationButton = QtWidgets.QPushButton(self.tab_2)
        self.projectLocationButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.projectLocationButton.setAutoDefault(False)
        self.projectLocationButton.setObjectName("projectLocationButton")
        self.horizontalLayout_14.addWidget(self.projectLocationButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.verticalLayout_20.addLayout(self.horizontalLayout_14)
        spacerItem12 = QtWidgets.QSpacerItem(20, 304, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_cell_type = QtWidgets.QWidget()
        self.tab_cell_type.setObjectName("tab_cell_type")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.tab_cell_type)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_cell_type)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.selectCellColorLabel = QtWidgets.QLabel(self.groupBox_14)
        self.selectCellColorLabel.setTextFormat(QtCore.Qt.PlainText)
        self.selectCellColorLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.selectCellColorLabel.setWordWrap(True)
        self.selectCellColorLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.selectCellColorLabel.setObjectName("selectCellColorLabel")
        self.verticalLayout_16.addWidget(self.selectCellColorLabel)
        self.typeColorTable = QtWidgets.QTableWidget(self.groupBox_14)
        self.typeColorTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeColorTable.sizePolicy().hasHeightForWidth())
        self.typeColorTable.setSizePolicy(sizePolicy)
        self.typeColorTable.setMinimumSize(QtCore.QSize(200, 0))
        self.typeColorTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.typeColorTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.typeColorTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.typeColorTable.setIconSize(QtCore.QSize(0, 0))
        self.typeColorTable.setShowGrid(True)
        self.typeColorTable.setWordWrap(False)
        self.typeColorTable.setCornerButtonEnabled(False)
        self.typeColorTable.setRowCount(20)
        self.typeColorTable.setColumnCount(3)
        self.typeColorTable.setObjectName("typeColorTable")
        item = QtWidgets.QTableWidgetItem()
        self.typeColorTable.setItem(0, 1, item)
        self.typeColorTable.horizontalHeader().setVisible(False)
        self.typeColorTable.horizontalHeader().setCascadingSectionResizes(True)
        self.typeColorTable.horizontalHeader().setDefaultSectionSize(50)
        self.typeColorTable.horizontalHeader().setHighlightSections(False)
        self.typeColorTable.verticalHeader().setVisible(False)
        self.typeColorTable.verticalHeader().setDefaultSectionSize(18)
        self.typeColorTable.verticalHeader().setHighlightSections(False)
        self.typeColorTable.verticalHeader().setMinimumSectionSize(11)
        self.typeColorTable.verticalHeader().setSortIndicatorShown(True)
        self.typeColorTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_16.addWidget(self.typeColorTable)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.addCellTypeButton = QtWidgets.QPushButton(self.groupBox_14)
        self.addCellTypeButton.setEnabled(True)
        self.addCellTypeButton.setAutoDefault(False)
        self.addCellTypeButton.setDefault(False)
        self.addCellTypeButton.setObjectName("addCellTypeButton")
        self.horizontalLayout_11.addWidget(self.addCellTypeButton)
        self.deleteCellTypeButton = QtWidgets.QPushButton(self.groupBox_14)
        self.deleteCellTypeButton.setEnabled(False)
        self.deleteCellTypeButton.setAutoDefault(False)
        self.deleteCellTypeButton.setObjectName("deleteCellTypeButton")
        self.horizontalLayout_11.addWidget(self.deleteCellTypeButton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addWidget(self.groupBox_14)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout.setObjectName("formLayout")
        self.borderColorLabel = QtWidgets.QLabel(self.groupBox_11)
        self.borderColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.borderColorLabel.setObjectName("borderColorLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.borderColorLabel)
        self.cellBorderColorButton = QtWidgets.QToolButton(self.groupBox_11)
        self.cellBorderColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.cellBorderColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.cellBorderColorButton.setText("")
        self.cellBorderColorButton.setObjectName("cellBorderColorButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cellBorderColorButton)
        self.clusterBorderColorLabel = QtWidgets.QLabel(self.groupBox_11)
        self.clusterBorderColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.clusterBorderColorLabel.setObjectName("clusterBorderColorLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.clusterBorderColorLabel)
        self.clusterBorderColorButton = QtWidgets.QToolButton(self.groupBox_11)
        self.clusterBorderColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.clusterBorderColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.clusterBorderColorButton.setText("")
        self.clusterBorderColorButton.setObjectName("clusterBorderColorButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.clusterBorderColorButton)
        self.contourColorLabel = QtWidgets.QLabel(self.groupBox_11)
        self.contourColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contourColorLabel.setObjectName("contourColorLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.contourColorLabel)
        self.contourColorButton = QtWidgets.QToolButton(self.groupBox_11)
        self.contourColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.contourColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.contourColorButton.setText("")
        self.contourColorButton.setObjectName("contourColorButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.contourColorButton)
        self.windowColorLabel = QtWidgets.QLabel(self.groupBox_11)
        self.windowColorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.windowColorLabel.setObjectName("windowColorLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.windowColorLabel)
        self.windowColorButton = QtWidgets.QToolButton(self.groupBox_11)
        self.windowColorButton.setEnabled(True)
        self.windowColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.windowColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.windowColorButton.setText("")
        self.windowColorButton.setObjectName("windowColorButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.windowColorButton)
        self.windowColorLabel_4 = QtWidgets.QLabel(self.groupBox_11)
        self.windowColorLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.windowColorLabel_4.setObjectName("windowColorLabel_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.windowColorLabel_4)
        self.fppColorButton = QtWidgets.QToolButton(self.groupBox_11)
        self.fppColorButton.setEnabled(True)
        self.fppColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.fppColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.fppColorButton.setText("")
        self.fppColorButton.setObjectName("fppColorButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fppColorButton)
        self.windowColorSameAsMediumCB = QtWidgets.QCheckBox(self.groupBox_11)
        self.windowColorSameAsMediumCB.setChecked(True)
        self.windowColorSameAsMediumCB.setObjectName("windowColorSameAsMediumCB")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.windowColorSameAsMediumCB)
        self.verticalLayout_17.addWidget(self.groupBox_11)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cellGlyphScaleByVolumeCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cellGlyphScaleByVolumeCheckBox.setObjectName("cellGlyphScaleByVolumeCheckBox")
        self.verticalLayout_11.addWidget(self.cellGlyphScaleByVolumeCheckBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.cellGlyphScale = QtWidgets.QLineEdit(self.groupBox_4)
        self.cellGlyphScale.setObjectName("cellGlyphScale")
        self.gridLayout.addWidget(self.cellGlyphScale, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.cellGlyphThetaRes = QtWidgets.QSpinBox(self.groupBox_4)
        self.cellGlyphThetaRes.setObjectName("cellGlyphThetaRes")
        self.gridLayout.addWidget(self.cellGlyphThetaRes, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.cellGlyphPhiRes = QtWidgets.QSpinBox(self.groupBox_4)
        self.cellGlyphPhiRes.setObjectName("cellGlyphPhiRes")
        self.gridLayout.addWidget(self.cellGlyphPhiRes, 2, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_17.addWidget(self.groupBox_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout_17)
        self.horizontalLayout_24.addWidget(self.groupBox_13)
        self.tabWidget.addTab(self.tab_cell_type, "")
        self.tab_field = QtWidgets.QWidget()
        self.tab_field.setObjectName("tab_field")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_field)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_field)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pixelizedScalarFieldCB = QtWidgets.QCheckBox(self.groupBox_6)
        self.pixelizedScalarFieldCB.setObjectName("pixelizedScalarFieldCB")
        self.horizontalLayout_28.addWidget(self.pixelizedScalarFieldCB)
        self.min_max_display_CB = QtWidgets.QCheckBox(self.groupBox_6)
        self.min_max_display_CB.setChecked(False)
        self.min_max_display_CB.setObjectName("min_max_display_CB")
        self.horizontalLayout_28.addWidget(self.min_max_display_CB)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.verticalLayout_15.addWidget(self.groupBox_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.tab_field)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.fieldComboBox = QtWidgets.QComboBox(self.tab_field)
        self.fieldComboBox.setObjectName("fieldComboBox")
        self.horizontalLayout_5.addWidget(self.fieldComboBox)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.showPlotAxesCB = QtWidgets.QCheckBox(self.tab_field)
        self.showPlotAxesCB.setObjectName("showPlotAxesCB")
        self.horizontalLayout_6.addWidget(self.showPlotAxesCB)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem14)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.line_3 = QtWidgets.QFrame(self.tab_field)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_15.addWidget(self.line_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem15 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_field)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.fieldMinLabel = QtWidgets.QLabel(self.groupBox_8)
        self.fieldMinLabel.setObjectName("fieldMinLabel")
        self.gridLayout_11.addWidget(self.fieldMinLabel, 0, 0, 1, 1)
        self.fieldMinRange = QtWidgets.QLineEdit(self.groupBox_8)
        self.fieldMinRange.setObjectName("fieldMinRange")
        self.gridLayout_11.addWidget(self.fieldMinRange, 0, 1, 1, 1)
        self.fieldMinRangeFixedCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.fieldMinRangeFixedCheckBox.setObjectName("fieldMinRangeFixedCheckBox")
        self.gridLayout_11.addWidget(self.fieldMinRangeFixedCheckBox, 0, 2, 1, 1)
        self.fieldMaxLabel = QtWidgets.QLabel(self.groupBox_8)
        self.fieldMaxLabel.setObjectName("fieldMaxLabel")
        self.gridLayout_11.addWidget(self.fieldMaxLabel, 1, 0, 1, 1)
        self.fieldMaxRange = QtWidgets.QLineEdit(self.groupBox_8)
        self.fieldMaxRange.setObjectName("fieldMaxRange")
        self.gridLayout_11.addWidget(self.fieldMaxRange, 1, 1, 1, 1)
        self.fieldMaxRangeFixedCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.fieldMaxRangeFixedCheckBox.setObjectName("fieldMaxRangeFixedCheckBox")
        self.gridLayout_11.addWidget(self.fieldMaxRangeFixedCheckBox, 1, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_11)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_field)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_18 = QtWidgets.QLabel(self.groupBox_9)
        self.label_18.setMinimumSize(QtCore.QSize(0, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_20.addWidget(self.label_18)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem16)
        self.vectorsArrowLength = QtWidgets.QSpinBox(self.groupBox_9)
        self.vectorsArrowLength.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsArrowLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vectorsArrowLength.setMaximum(9999)
        self.vectorsArrowLength.setObjectName("vectorsArrowLength")
        self.horizontalLayout_20.addWidget(self.vectorsArrowLength)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.vectorsScaleArrowCheckBox = QtWidgets.QCheckBox(self.groupBox_9)
        self.vectorsScaleArrowCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsScaleArrowCheckBox.setObjectName("vectorsScaleArrowCheckBox")
        self.horizontalLayout_19.addWidget(self.vectorsScaleArrowCheckBox)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem17)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.vectorsArrowColorCheckBox = QtWidgets.QCheckBox(self.groupBox_9)
        self.vectorsArrowColorCheckBox.setMinimumSize(QtCore.QSize(0, 30))
        self.vectorsArrowColorCheckBox.setObjectName("vectorsArrowColorCheckBox")
        self.horizontalLayout_18.addWidget(self.vectorsArrowColorCheckBox)
        self.vectorsArrowColorButton = QtWidgets.QToolButton(self.groupBox_9)
        self.vectorsArrowColorButton.setMinimumSize(QtCore.QSize(26, 26))
        self.vectorsArrowColorButton.setMaximumSize(QtCore.QSize(26, 26))
        self.vectorsArrowColorButton.setText("")
        self.vectorsArrowColorButton.setObjectName("vectorsArrowColorButton")
        self.horizontalLayout_18.addWidget(self.vectorsArrowColorButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.vectorsOverlayCheckBox = QtWidgets.QCheckBox(self.tab_field)
        self.vectorsOverlayCheckBox.setObjectName("vectorsOverlayCheckBox")
        self.verticalLayout_2.addWidget(self.vectorsOverlayCheckBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_field)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.fieldLegendNumLabels = QtWidgets.QSpinBox(self.groupBox_7)
        self.fieldLegendNumLabels.setMinimumSize(QtCore.QSize(0, 30))
        self.fieldLegendNumLabels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fieldLegendNumLabels.setMaximum(9999)
        self.fieldLegendNumLabels.setObjectName("fieldLegendNumLabels")
        self.horizontalLayout_7.addWidget(self.fieldLegendNumLabels)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.fieldLegendAccuracy = QtWidgets.QSpinBox(self.groupBox_7)
        self.fieldLegendAccuracy.setMinimumSize(QtCore.QSize(0, 30))
        self.fieldLegendAccuracy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fieldLegendAccuracy.setMaximum(9999)
        self.fieldLegendAccuracy.setObjectName("fieldLegendAccuracy")
        self.horizontalLayout_8.addWidget(self.fieldLegendAccuracy)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.fieldShowLegendCheckBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.fieldShowLegendCheckBox.setObjectName("fieldShowLegendCheckBox")
        self.horizontalLayout_9.addWidget(self.fieldShowLegendCheckBox)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem19)
        self.gridLayout_7.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_field)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.numIsovalsInRangeLabel = QtWidgets.QLabel(self.groupBox_12)
        self.numIsovalsInRangeLabel.setObjectName("numIsovalsInRangeLabel")
        self.gridLayout_10.addWidget(self.numIsovalsInRangeLabel, 2, 0, 1, 1)
        self.numberOfContoursLinesSpinBox = QtWidgets.QSpinBox(self.groupBox_12)
        self.numberOfContoursLinesSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfContoursLinesSpinBox.setMaximum(9999)
        self.numberOfContoursLinesSpinBox.setObjectName("numberOfContoursLinesSpinBox")
        self.gridLayout_10.addWidget(self.numberOfContoursLinesSpinBox, 2, 1, 1, 1)
        self.isovalList = QtWidgets.QLineEdit(self.groupBox_12)
        self.isovalList.setObjectName("isovalList")
        self.gridLayout_10.addWidget(self.isovalList, 1, 1, 1, 1)
        self.isovalLabel = QtWidgets.QLabel(self.groupBox_12)
        self.isovalLabel.setObjectName("isovalLabel")
        self.gridLayout_10.addWidget(self.isovalLabel, 1, 0, 1, 1)
        self.contoursShowCB = QtWidgets.QCheckBox(self.groupBox_12)
        self.contoursShowCB.setObjectName("contoursShowCB")
        self.gridLayout_10.addWidget(self.contoursShowCB, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem20)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_15)
        self.tabWidget.addTab(self.tab_field, "")
        self.tab_3D = QtWidgets.QWidget()
        self.tab_3D.setObjectName("tab_3D")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_3D)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem21 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem21)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3D)
        self.groupBox.setEnabled(False)
        self.groupBox.setMinimumSize(QtCore.QSize(110, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 91, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(25, 30))
        self.spinBox.setSpecialValueText("")
        self.spinBox.setMaximum(999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_5.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_2.setMaximum(999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_5.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_3.setMaximum(999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_5.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem22 = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem22)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3D)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_6.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_6.setSpecialValueText("")
        self.spinBox_6.setMaximum(999)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_3.addWidget(self.spinBox_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_7.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_7.setMaximum(999)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_3.addWidget(self.spinBox_7, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_8.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_8.setMaximum(999)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_3.addWidget(self.spinBox_8, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        spacerItem23 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3D)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(2, 1, 2, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cellTypesInvisibleList = QtWidgets.QLineEdit(self.groupBox_2)
        self.cellTypesInvisibleList.setObjectName("cellTypesInvisibleList")
        self.horizontalLayout.addWidget(self.cellTypesInvisibleList)
        self.verticalLayout_22.addWidget(self.groupBox_2)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_27.addLayout(self.verticalLayout_4)
        spacerItem24 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem24)
        self.verticalLayout_22.addLayout(self.horizontalLayout_27)
        spacerItem25 = QtWidgets.QSpacerItem(20, 103, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem25)
        self.tabWidget.addTab(self.tab_3D, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.boundingBoxCheckBox = QtWidgets.QCheckBox(self.groupBox_10)
        self.boundingBoxCheckBox.setObjectName("boundingBoxCheckBox")
        self.horizontalLayout_29.addWidget(self.boundingBoxCheckBox)
        spacerItem26 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem26)
        self.label_12 = QtWidgets.QLabel(self.groupBox_10)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_29.addWidget(self.label_12)
        self.boundingBoxColorButton = QtWidgets.QToolButton(self.groupBox_10)
        self.boundingBoxColorButton.setEnabled(True)
        self.boundingBoxColorButton.setText("")
        self.boundingBoxColorButton.setObjectName("boundingBoxColorButton")
        self.horizontalLayout_29.addWidget(self.boundingBoxColorButton)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.verticalLayout_24.addWidget(self.groupBox_10)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.showAxesCB = QtWidgets.QCheckBox(self.groupBox_15)
        self.showAxesCB.setObjectName("showAxesCB")
        self.horizontalLayout_30.addWidget(self.showAxesCB)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem27)
        self.label_21 = QtWidgets.QLabel(self.groupBox_15)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_30.addWidget(self.label_21)
        self.axesColorButton = QtWidgets.QToolButton(self.groupBox_15)
        self.axesColorButton.setEnabled(True)
        self.axesColorButton.setText("")
        self.axesColorButton.setObjectName("axesColorButton")
        self.horizontalLayout_30.addWidget(self.axesColorButton)
        self.verticalLayout_23.addLayout(self.horizontalLayout_30)
        self.showHorizontalAxesLabelsCB = QtWidgets.QCheckBox(self.groupBox_15)
        self.showHorizontalAxesLabelsCB.setObjectName("showHorizontalAxesLabelsCB")
        self.verticalLayout_23.addWidget(self.showHorizontalAxesLabelsCB)
        self.showVerticalAxesLabelsCB = QtWidgets.QCheckBox(self.groupBox_15)
        self.showVerticalAxesLabelsCB.setObjectName("showVerticalAxesLabelsCB")
        self.verticalLayout_23.addWidget(self.showVerticalAxesLabelsCB)
        self.verticalLayout_24.addWidget(self.groupBox_15)
        self.gridLayout_2.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(201, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem28, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 172, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem29, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_18.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(CC3DPrefs)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_18.addWidget(self.buttonBox)

        self.retranslateUi(CC3DPrefs)
        self.tabWidget.setCurrentIndex(5)
        self.contoursShowCB.toggled['bool'].connect(self.isovalList.setEnabled)
        self.contoursShowCB.toggled['bool'].connect(self.numberOfContoursLinesSpinBox.setEnabled)
        self.buttonBox.rejected.connect(CC3DPrefs.reject)
        self.buttonBox.accepted.connect(CC3DPrefs.accept)
        self.restart_CB.toggled['bool'].connect(self.restart_freq_SB.setEnabled)
        self.restart_CB.toggled['bool'].connect(self.multiple_restart_snapshots_CB.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CC3DPrefs)

    def retranslateUi(self, CC3DPrefs):
        _translate = QtCore.QCoreApplication.translate
        CC3DPrefs.setWindowTitle(_translate("CC3DPrefs", "CC3D Preferences"))
        self.tabWidget.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_17.setTitle(_translate("CC3DPrefs", "Output Specs"))
        self.label_5.setText(_translate("CC3DPrefs", "Update screen every Nth MCS"))
        self.updateScreenSpinBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Frequency with which player will display scenes</p></body></html>"))
        self.outputImagesCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables screenshot output</p></body></html>"))
        self.outputImagesCheckBox.setText(_translate("CC3DPrefs", "Save image every Nth MCS"))
        self.saveImageSpinBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Screenshot output frequency</p></body></html>"))
        self.label_13.setText(_translate("CC3DPrefs", "Screenshot Resolution     "))
        self.label_16.setText(_translate("CC3DPrefs", "X"))
        self.screenshot_X_SB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Screenshot resolution (x-size)</p></body></html>"))
        self.label_17.setText(_translate("CC3DPrefs", "Y"))
        self.screenshot_Y_SB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Screenshot resolution (y-size)</p></body></html>"))
        self.outputLatticeDataCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables taking complete visualization snapshots (those can pbe replayed in player after simulation is doena dn you can take any screenshots you want at that point)</p></body></html>"))
        self.outputLatticeDataCheckBox.setText(_translate("CC3DPrefs", "Save visualization snapshots every Nth MCS"))
        self.saveLatticeSpinBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Visualization snapshot write frequency</p></body></html>"))
        self.label_19.setText(_translate("CC3DPrefs", "Workspace Dir"))
        self.outputLocationLineEdit.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Directory where simulation outputs will be written to</p></body></html>"))
        self.outputLocationButton.setText(_translate("CC3DPrefs", "Output"))
        self.outputToProjectCheckBox.setText(_translate("CC3DPrefs", "=Project"))
        self.debugOutputPlayerCB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>enables player debug output (deprecated)</p></body></html>"))
        self.debugOutputPlayerCB.setText(_translate("CC3DPrefs", "Turn On Player Debug Output"))
        self.useInternalConsoleCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>enables using internal player console for output (half-deprrecated)</p></body></html>"))
        self.useInternalConsoleCheckBox.setText(_translate("CC3DPrefs", "Use internal console for text output"))
        self.closePlayerCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>If checked this will cause player close after simulation is done</p></body></html>"))
        self.closePlayerCheckBox.setText(_translate("CC3DPrefs", "Close Player after simulation ends"))
        self.groupBox_16.setTitle(_translate("CC3DPrefs", "Restart"))
        self.restart_CB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables output of restart snapshots. Those can be used to restart your simulation from the point at which simulation snapshot was taken. This is not a visualization snapshot</p></body></html>"))
        self.restart_CB.setText(_translate("CC3DPrefs", "Enable output of restart snapshots"))
        self.label_20.setText(_translate("CC3DPrefs", "Restart Output Frequency"))
        self.restart_freq_SB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Restart snaphot frequency</p></body></html>"))
        self.multiple_restart_snapshots_CB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>If checked multiple restart snapshots will be taken. </p></body></html>"))
        self.multiple_restart_snapshots_CB.setText(_translate("CC3DPrefs", "Allow multiple restart snapshots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_output), _translate("CC3DPrefs", "Output"))
        self.groupBox_5.setTitle(_translate("CC3DPrefs", "Miscellaneous"))
        self.label_23.setText(_translate("CC3DPrefs", "Number of recent simulations"))
        self.floatingWindowsCB.setToolTip(_translate("CC3DPrefs", "Checking it switches from Multi Document interface to flowting windows one. The change will take place after Player restart"))
        self.floatingWindowsCB.setText(_translate("CC3DPrefs", "Use Floating Windows"))
        self.label_22.setText(_translate("CC3DPrefs", "Number of step outputs to display in player"))
        self.numberOfStepOutputsSB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Number of recent MCS steps for which the operating system console output will be also displayed in the Player console</p></body></html>"))
        self.numberOfRecentSimulationsSB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Number of recent simulations to display in the &quot;Recent Simulation&quot; menu</p></body></html>"))
        self.projectLocationLineEdit.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>directory where most of your projects are stored</p></body></html>"))
        self.projectLocationButton.setText(_translate("CC3DPrefs", "Project Location"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CC3DPrefs", "General Settings"))
        self.groupBox_14.setTitle(_translate("CC3DPrefs", "Cell Types and Colors"))
        self.selectCellColorLabel.setText(_translate("CC3DPrefs", "Select a row in the table to change that cell type color.   Type        Name           Color"))
        __sortingEnabled = self.typeColorTable.isSortingEnabled()
        self.typeColorTable.setSortingEnabled(False)
        self.typeColorTable.setSortingEnabled(__sortingEnabled)
        self.addCellTypeButton.setText(_translate("CC3DPrefs", "Add"))
        self.deleteCellTypeButton.setText(_translate("CC3DPrefs", "-"))
        self.groupBox_11.setTitle(_translate("CC3DPrefs", "Aditional colors"))
        self.borderColorLabel.setText(_translate("CC3DPrefs", "Cell border color"))
        self.cellBorderColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets cell boundary color</p></body></html>"))
        self.clusterBorderColorLabel.setText(_translate("CC3DPrefs", "Cluster border color"))
        self.clusterBorderColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets cell cluster boundary color</p></body></html>"))
        self.contourColorLabel.setText(_translate("CC3DPrefs", "Contour color"))
        self.contourColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets chemical field contour color</p></body></html>"))
        self.windowColorLabel.setText(_translate("CC3DPrefs", "Window color"))
        self.windowColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets background color for the graphics window</p></body></html>"))
        self.windowColorLabel_4.setText(_translate("CC3DPrefs", "FPP Link Color"))
        self.fppColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets FPP link color</p></body></html>"))
        self.windowColorSameAsMediumCB.setText(_translate("CC3DPrefs", "Window color same as Medium"))
        self.groupBox_4.setTitle(_translate("CC3DPrefs", "Cell Glyphs"))
        self.cellGlyphScaleByVolumeCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>When drawing cells as spheres (glyphs) this setting allows scaling of the size of the sphere based on actual cell volume</p></body></html>"))
        self.cellGlyphScaleByVolumeCheckBox.setText(_translate("CC3DPrefs", "scale by volume"))
        self.label_9.setText(_translate("CC3DPrefs", "Scale factor"))
        self.cellGlyphScale.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Scale of sphere representing a cell </p></body></html>"))
        self.label_10.setText(_translate("CC3DPrefs", "Theta res"))
        self.cellGlyphThetaRes.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>part of accuracy metric that is used to determing how a sphere representing sphere will be rendered. The higher the nices sphere will look , but rendering will also be slower</p></body></html>"))
        self.label_11.setText(_translate("CC3DPrefs", "Phi res"))
        self.cellGlyphPhiRes.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>part of accuracy metric that is used to determing how a sphere representing sphere will be rendered. The higher the nices sphere will look , but rendering will also be slower</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cell_type), _translate("CC3DPrefs", "Cells/Colors"))
        self.groupBox_6.setTitle(_translate("CC3DPrefs", "General properties"))
        self.pixelizedScalarFieldCB.setToolTip(_translate("CC3DPrefs", "Checking this box will cause cartesian concentration field in 2D be drawn using explicit pixels providing \"exact\" representation of the field. Unchecked box will mean that field will be smoothed. "))
        self.pixelizedScalarFieldCB.setText(_translate("CC3DPrefs", "Pixelized (\"exact\") cartesian fields (including cell field)  "))
        self.min_max_display_CB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables display of min and max concentration directly in the chemical field window</p></body></html>"))
        self.min_max_display_CB.setText(_translate("CC3DPrefs", "Display Min Max Field Values"))
        self.label_6.setText(_translate("CC3DPrefs", "Field name:"))
        self.showPlotAxesCB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables display of axes in a give field</p></body></html>"))
        self.showPlotAxesCB.setText(_translate("CC3DPrefs", "Show Axes"))
        self.groupBox_8.setTitle(_translate("CC3DPrefs", "Range (of magnitude for vectors)"))
        self.fieldMinLabel.setText(_translate("CC3DPrefs", "Min"))
        self.fieldMinRange.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Min concentration (or vector length) threshold that will be used to determine heatmap colors for concentration or vector fields</p></body></html>"))
        self.fieldMinRangeFixedCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables concentration (or vector length) threshold that will be used to determine heatmap colors for concentration or vector fields</p></body></html>"))
        self.fieldMinRangeFixedCheckBox.setText(_translate("CC3DPrefs", "Fixed"))
        self.fieldMaxLabel.setText(_translate("CC3DPrefs", "Max"))
        self.fieldMaxRange.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Min concentration (or vector length) threshold that will be used to determine heatmap colors for concentration or vector fields</p></body></html>"))
        self.fieldMaxRangeFixedCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables concentration (or vector length) threshold that will be used to determine heatmap colors for concentration or vector fields</p></body></html>"))
        self.fieldMaxRangeFixedCheckBox.setText(_translate("CC3DPrefs", "Fixed"))
        self.groupBox_9.setTitle(_translate("CC3DPrefs", "Vector Arrows"))
        self.label_18.setText(_translate("CC3DPrefs", "Length"))
        self.vectorsArrowLength.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Arrow length for displaying vector fields</p></body></html>"))
        self.vectorsScaleArrowCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Determines if arrow length will be scaled by the vector length that arrow is prepresenting</p></body></html>"))
        self.vectorsScaleArrowCheckBox.setText(_translate("CC3DPrefs", "Scale arrow length"))
        self.vectorsArrowColorCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Determines if arrow color will be deterined by the heatmap colors or if it will be fixed</p></body></html>"))
        self.vectorsArrowColorCheckBox.setText(_translate("CC3DPrefs", "Fixed arrow color"))
        self.vectorsArrowColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets arrow color if it i set to be fixed</p></body></html>"))
        self.vectorsOverlayCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>decides if cell and vector fields should be ploted in the same scene</p></body></html>"))
        self.vectorsOverlayCheckBox.setText(_translate("CC3DPrefs", "Overlay Vector and Cell Field"))
        self.groupBox_7.setTitle(_translate("CC3DPrefs", "Legend"))
        self.label_14.setText(_translate("CC3DPrefs", "# of labels"))
        self.fieldLegendNumLabels.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>number of &quot;boxes&quot; in heatmap legend</p></body></html>"))
        self.label_15.setText(_translate("CC3DPrefs", "Accuracy"))
        self.fieldShowLegendCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables display of heatmap legend</p></body></html>"))
        self.fieldShowLegendCheckBox.setText(_translate("CC3DPrefs", "Show "))
        self.groupBox_12.setTitle(_translate("CC3DPrefs", "Scalar Contours"))
        self.numIsovalsInRangeLabel.setText(_translate("CC3DPrefs", "Over range"))
        self.numberOfContoursLinesSpinBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>number of contour lines (isovalues will be chosen automatically)</p></body></html>"))
        self.isovalList.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Comma-separated list of isovalues for plotting contours</p></body></html>"))
        self.isovalLabel.setText(_translate("CC3DPrefs", "Isovalues"))
        self.contoursShowCB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>enables display of contours for scalar fields</p></body></html>"))
        self.contoursShowCB.setText(_translate("CC3DPrefs", "Show"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_field), _translate("CC3DPrefs", "Field"))
        self.groupBox.setTitle(_translate("CC3DPrefs", "Display Size"))
        self.label.setText(_translate("CC3DPrefs", "X"))
        self.label_2.setText(_translate("CC3DPrefs", "Y"))
        self.label_3.setText(_translate("CC3DPrefs", "Z"))
        self.groupBox_3.setTitle(_translate("CC3DPrefs", "Camera"))
        self.label_4.setText(_translate("CC3DPrefs", "Elevation"))
        self.label_7.setText(_translate("CC3DPrefs", "Azimuth"))
        self.label_8.setText(_translate("CC3DPrefs", "Roll"))
        self.groupBox_2.setTitle(_translate("CC3DPrefs", "Cell types invisible in 3D (example: 0,1,4)"))
        self.cellTypesInvisibleList.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>comma-sepoarated list of cell type numbers that shuold not be rendered in 3D. Usually you do not want to display medium so at the very least this list should have \'0\' element in it</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3D), _translate("CC3DPrefs", "3D"))
        self.groupBox_10.setTitle(_translate("CC3DPrefs", "Bounding Box"))
        self.boundingBoxCheckBox.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>enables display ob scene bounding box - a line around lattice</p></body></html>"))
        self.boundingBoxCheckBox.setText(_translate("CC3DPrefs", "Bounding Box Outline"))
        self.label_12.setText(_translate("CC3DPrefs", "    Color"))
        self.boundingBoxColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets bounding box color</p></body></html>"))
        self.groupBox_15.setTitle(_translate("CC3DPrefs", "Axes"))
        self.showAxesCB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>Enables display of axed</p></body></html>"))
        self.showAxesCB.setText(_translate("CC3DPrefs", "Show Axes"))
        self.label_21.setText(_translate("CC3DPrefs", "    Color"))
        self.axesColorButton.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>sets axes color</p></body></html>"))
        self.showHorizontalAxesLabelsCB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>enables x-axes labels (in 2D)</p></body></html>"))
        self.showHorizontalAxesLabelsCB.setText(_translate("CC3DPrefs", "Show Horizontal Axes Labels (2D)"))
        self.showVerticalAxesLabelsCB.setToolTip(_translate("CC3DPrefs", "<html><head/><body><p>enables y-axes labels (in 2D)</p></body></html>"))
        self.showVerticalAxesLabelsCB.setText(_translate("CC3DPrefs", "Show Vertical Axes Labels (2D)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CC3DPrefs", "Axes\'n\'Decor"))
