from cc3d import CompuCellSetup
from .SBMLSolverAntimony3Steppables import SBMLSolverSteppable
from .SBMLSolverAntimony3Steppables import IdFieldVisualizationSteppable
from .SBMLSolverAntimony3Steppables import SecretionSteppable
from .SBMLSolverAntimony3Steppables import DeltaNotchNeighborSteppable
from .SBMLSolverAntimony3Steppables import NotchChemotaxisSteppable


CompuCellSetup.register_steppable(steppable=SBMLSolverSteppable(frequency=1))

CompuCellSetup.register_steppable(steppable=IdFieldVisualizationSteppable(frequency=1))

CompuCellSetup.register_steppable(steppable=SecretionSteppable(frequency=1))

CompuCellSetup.register_steppable(steppable=DeltaNotchNeighborSteppable(frequency=1))

CompuCellSetup.register_steppable(steppable=NotchChemotaxisSteppable(frequency=1))


CompuCellSetup.run()
