(CELL_FIELD, CON_FIELD, SCALAR_FIELD, SCALAR_FIELD_CELL_LEVEL, VECTOR_FIELD, VECTOR_FIELD_CELL_LEVEL,SCALAR_FIELD_NPY,VECTOR_FIELD_NPY)=range(0,8)
(LEGACY_FORMAT,CSV_FORMAT)=range(0,2)

GRAPHICS_WINDOW_LABEL, PLOT_WINDOW_LABEL = ('Graphics', 'Plot')