{% set version = "4.3.0" %}


package:
  name: compucell3d
  version: {{ version }}

about:
  home: https://compucell3d.org
  license: GPL
  summary: Multiscale multicellular virtual tissue modeling and simulation environment

extra:
  maintainers: T.J. Sego, Maciek Swat

source:
  # url: https://github.com/CompuCell3D/CompuCell3D/archive/master.tar.gz
  path: ../

build:
  number: 12

requirements:
  host:
    - python=3.7
#    - cc3d {{ version }}
#    - cc3d-player5 {{ version }}
    - cc3d-twedit5 {{ version }}.*

#  build:
#    - cc3d {{ version }}
#    - cc3d-player5 {{ version }}
#    - cc3d-twedit5 {{ version }}


  run:
    - python=3.7
#    - cc3d {{ version }}
#    - cc3d-player5 {{ version }}
    - cc3d-twedit5 {{ version }}.*

test:
  imports:
    - sys
    - cc3d
