import cc3d.CompuCellSetup as CompuCellSetup

from FocalPointPlasticityCompartmentsSteppables import FocalPointPlasticityCompartmentsSteppable

CompuCellSetup.register_steppable(steppable=FocalPointPlasticityCompartmentsSteppable(frequency=1))

CompuCellSetup.run()

