#include "CurvatureCalculatorPlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto curvatureCalculatorProxy = registerPlugin<Plugin, CurvatureCalculatorPlugin>(
    "CurvatureCalculator", 
    "Autogenerated plugin - the author of the plugin should provide brief description here", 
    &Simulator::pluginManager
);
