from cc3d import CompuCellSetup

from diffusion_2D_scale_OpenCLSteppables import diffusion_2D_scale_OpenCLSteppable

CompuCellSetup.register_steppable(steppable=diffusion_2D_scale_OpenCLSteppable(frequency=1))

CompuCellSetup.run()
