#include "CleaverMeshDumper.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto cleaverMeshDumperProxy = registerPlugin<Steppable, CleaverMeshDumper>(
	"CleaverMeshDumper", 
	"Autogenerated steppeble - the author of the plugin should provide brief description here",
	&Simulator::steppableManager
);
