# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pottsdlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PottsGUI(object):
    def setupUi(self, PottsGUI):
        PottsGUI.setObjectName("PottsGUI")
        PottsGUI.resize(353, 406)
        self.gridLayout = QtWidgets.QGridLayout(PottsGUI)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tabWidget = QtWidgets.QTabWidget(PottsGUI)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_general)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_general)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_24.addWidget(self.label_28)
        self.xDimSB = QtWidgets.QSpinBox(self.groupBox_7)
        self.xDimSB.setMinimum(1)
        self.xDimSB.setMaximum(10000000)
        self.xDimSB.setProperty("value", 256)
        self.xDimSB.setObjectName("xDimSB")
        self.horizontalLayout_24.addWidget(self.xDimSB)
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_24.addWidget(self.label_29)
        self.yDimSB = QtWidgets.QSpinBox(self.groupBox_7)
        self.yDimSB.setMinimum(1)
        self.yDimSB.setMaximum(10000000)
        self.yDimSB.setProperty("value", 256)
        self.yDimSB.setObjectName("yDimSB")
        self.horizontalLayout_24.addWidget(self.yDimSB)
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_24.addWidget(self.label_30)
        self.zDimSB = QtWidgets.QSpinBox(self.groupBox_7)
        self.zDimSB.setMinimum(1)
        self.zDimSB.setMaximum(10000000)
        self.zDimSB.setObjectName("zDimSB")
        self.horizontalLayout_24.addWidget(self.zDimSB)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_24)
        self.gridLayout_2.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_general)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.xbcCB = QtWidgets.QComboBox(self.groupBox_3)
        self.xbcCB.setObjectName("xbcCB")
        self.xbcCB.addItem("")
        self.xbcCB.addItem("")
        self.horizontalLayout_11.addWidget(self.xbcCB)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.ybcCB = QtWidgets.QComboBox(self.groupBox_3)
        self.ybcCB.setObjectName("ybcCB")
        self.ybcCB.addItem("")
        self.ybcCB.addItem("")
        self.horizontalLayout_11.addWidget(self.ybcCB)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.zbcCB = QtWidgets.QComboBox(self.groupBox_3)
        self.zbcCB.setObjectName("zbcCB")
        self.zbcCB.addItem("")
        self.zbcCB.addItem("")
        self.horizontalLayout_11.addWidget(self.zbcCB)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_33 = QtWidgets.QLabel(self.tab_general)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_general)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 0, 1, 1)
        self.mcsSB = QtWidgets.QSpinBox(self.tab_general)
        self.mcsSB.setMaximum(1000000000)
        self.mcsSB.setProperty("value", 100000)
        self.mcsSB.setObjectName("mcsSB")
        self.gridLayout_6.addWidget(self.mcsSB, 5, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_general)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 0, 0, 1, 1)
        self.latticeTypeCB = QtWidgets.QComboBox(self.tab_general)
        self.latticeTypeCB.setObjectName("latticeTypeCB")
        self.latticeTypeCB.addItem("")
        self.latticeTypeCB.addItem("")
        self.gridLayout_6.addWidget(self.latticeTypeCB, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_general)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 4, 0, 1, 1)
        self.fluctuation_FcnCB = QtWidgets.QComboBox(self.tab_general)
        self.fluctuation_FcnCB.setObjectName("fluctuation_FcnCB")
        self.gridLayout_6.addWidget(self.fluctuation_FcnCB, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_general)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 3, 0, 1, 1)
        self.membraneFluctuationsLE = QtWidgets.QLineEdit(self.tab_general)
        self.membraneFluctuationsLE.setObjectName("membraneFluctuationsLE")
        self.gridLayout_6.addWidget(self.membraneFluctuationsLE, 3, 1, 1, 1)
        self.neighborOrderSB = QtWidgets.QSpinBox(self.tab_general)
        self.neighborOrderSB.setMinimum(1)
        self.neighborOrderSB.setMaximum(10)
        self.neighborOrderSB.setProperty("value", 1)
        self.neighborOrderSB.setObjectName("neighborOrderSB")
        self.gridLayout_6.addWidget(self.neighborOrderSB, 4, 1, 1, 1)
        self.cell_TypeCB = QtWidgets.QComboBox(self.tab_general)
        self.cell_TypeCB.setObjectName("cell_TypeCB")
        self.gridLayout_6.addWidget(self.cell_TypeCB, 2, 0, 1, 1)
        self.type_ParamLE = QtWidgets.QLineEdit(self.tab_general)
        self.type_ParamLE.setObjectName("type_ParamLE")
        self.gridLayout_6.addWidget(self.type_ParamLE, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_advanced = QtWidgets.QWidget()
        self.tab_advanced.setObjectName("tab_advanced")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_advanced)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_advanced)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.offset_SB = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.offset_SB.setMinimum(-99990000.0)
        self.offset_SB.setMaximum(99990000.0)
        self.offset_SB.setObjectName("offset_SB")
        self.horizontalLayout.addWidget(self.offset_SB)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.coefficient_SB = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.coefficient_SB.setMaximum(99990000.0)
        self.coefficient_SB.setProperty("value", 1.0)
        self.coefficient_SB.setObjectName("coefficient_SB")
        self.horizontalLayout.addWidget(self.coefficient_SB)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_advanced)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.anneal_SB = QtWidgets.QSpinBox(self.groupBox_2)
        self.anneal_SB.setMaximum(99999999)
        self.anneal_SB.setObjectName("anneal_SB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.anneal_SB)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.flip_to_dim_SB = QtWidgets.QSpinBox(self.groupBox_2)
        self.flip_to_dim_SB.setMinimum(1)
        self.flip_to_dim_SB.setMaximum(99999999)
        self.flip_to_dim_SB.setObjectName("flip_to_dim_SB")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.flip_to_dim_SB)
        self.debug_SB = QtWidgets.QSpinBox(self.groupBox_2)
        self.debug_SB.setMinimum(1)
        self.debug_SB.setMaximum(99999999)
        self.debug_SB.setObjectName("debug_SB")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.debug_SB)
        self.random_seed_SB = QtWidgets.QSpinBox(self.groupBox_2)
        self.random_seed_SB.setMinimum(0)
        self.random_seed_SB.setMaximum(99999999)
        self.random_seed_SB.setProperty("value", 0)
        self.random_seed_SB.setObjectName("random_seed_SB")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.random_seed_SB)
        self.random_seed_CB = QtWidgets.QCheckBox(self.groupBox_2)
        self.random_seed_CB.setObjectName("random_seed_CB")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.random_seed_CB)
        self.debug_CB = QtWidgets.QCheckBox(self.groupBox_2)
        self.debug_CB.setObjectName("debug_CB")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.debug_CB)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_advanced)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ef_results_CB = QtWidgets.QCheckBox(self.groupBox_4)
        self.ef_results_CB.setObjectName("ef_results_CB")
        self.gridLayout_5.addWidget(self.ef_results_CB, 1, 0, 1, 1)
        self.ef_enable_CB = QtWidgets.QCheckBox(self.groupBox_4)
        self.ef_enable_CB.setObjectName("ef_enable_CB")
        self.gridLayout_5.addWidget(self.ef_enable_CB, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ef_accepted_CB = QtWidgets.QCheckBox(self.groupBox_4)
        self.ef_accepted_CB.setMinimumSize(QtCore.QSize(0, 0))
        self.ef_accepted_CB.setObjectName("ef_accepted_CB")
        self.horizontalLayout_5.addWidget(self.ef_accepted_CB)
        self.ef_rejected_CB = QtWidgets.QCheckBox(self.groupBox_4)
        self.ef_rejected_CB.setMinimumSize(QtCore.QSize(0, 0))
        self.ef_rejected_CB.setObjectName("ef_rejected_CB")
        self.horizontalLayout_5.addWidget(self.ef_rejected_CB)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.ef_total_CB = QtWidgets.QCheckBox(self.groupBox_4)
        self.ef_total_CB.setObjectName("ef_total_CB")
        self.gridLayout_5.addWidget(self.ef_total_CB, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 1, 1, 1)
        self.ef_spin_freq_SB = QtWidgets.QSpinBox(self.groupBox_4)
        self.ef_spin_freq_SB.setMinimum(1)
        self.ef_spin_freq_SB.setMaximum(99999999)
        self.ef_spin_freq_SB.setObjectName("ef_spin_freq_SB")
        self.gridLayout_5.addWidget(self.ef_spin_freq_SB, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.ef_file_name_LE = QtWidgets.QLineEdit(self.groupBox_4)
        self.ef_file_name_LE.setObjectName("ef_file_name_LE")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ef_file_name_LE)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.ef_file_freq_SB = QtWidgets.QSpinBox(self.groupBox_4)
        self.ef_file_freq_SB.setMinimum(1)
        self.ef_file_freq_SB.setMaximum(99999999)
        self.ef_file_freq_SB.setObjectName("ef_file_freq_SB")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ef_file_freq_SB)
        self.gridLayout_8.addLayout(self.formLayout_2, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_advanced, "")
        self.verticalLayout_19.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PottsGUI)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_19.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout_19, 0, 1, 1, 1)

        self.retranslateUi(PottsGUI)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PottsGUI)

    def retranslateUi(self, PottsGUI):
        _translate = QtCore.QCoreApplication.translate
        PottsGUI.setWindowTitle(_translate("PottsGUI", "Potts: Please define CPM configuration"))
        self.groupBox_7.setTitle(_translate("PottsGUI", "Lattice Dimensions"))
        self.label_28.setText(_translate("PottsGUI", "x"))
        self.label_29.setText(_translate("PottsGUI", "y"))
        self.label_30.setText(_translate("PottsGUI", "z"))
        self.groupBox_3.setTitle(_translate("PottsGUI", "Boundary Conditions (Cell Lattice)"))
        self.label_13.setText(_translate("PottsGUI", "x"))
        self.xbcCB.setItemText(0, _translate("PottsGUI", "NoFlux"))
        self.xbcCB.setItemText(1, _translate("PottsGUI", "Periodic"))
        self.label_14.setText(_translate("PottsGUI", "y"))
        self.ybcCB.setItemText(0, _translate("PottsGUI", "NoFlux"))
        self.ybcCB.setItemText(1, _translate("PottsGUI", "Periodic"))
        self.label_15.setText(_translate("PottsGUI", "z"))
        self.zbcCB.setItemText(0, _translate("PottsGUI", "NoFlux"))
        self.zbcCB.setItemText(1, _translate("PottsGUI", "Periodic"))
        self.label_33.setText(_translate("PottsGUI", "Number of MC Steps"))
        self.label.setText(_translate("PottsGUI", "Fluctuation Function"))
        self.label_44.setText(_translate("PottsGUI", "LatticeType"))
        self.latticeTypeCB.setItemText(0, _translate("PottsGUI", "Square"))
        self.latticeTypeCB.setItemText(1, _translate("PottsGUI", "Hexagonal"))
        self.label_32.setText(_translate("PottsGUI", "Pixel Copy Range (NeighborOrder)"))
        self.label_31.setText(_translate("PottsGUI", "Average Membrane Fluctuations"))
        self.membraneFluctuationsLE.setToolTip(_translate("PottsGUI", "Also known as so called temperature parameter in the acceptance probability expresion:  exp(-delta E/(k*T))"))
        self.membraneFluctuationsLE.setText(_translate("PottsGUI", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general), _translate("PottsGUI", "General"))
        self.groupBox.setTitle(_translate("PottsGUI", "Boltzmann Acceptance"))
        self.label_3.setText(_translate("PottsGUI", "Offset"))
        self.label_2.setText(_translate("PottsGUI", "Coefficient"))
        self.groupBox_2.setTitle(_translate("PottsGUI", "Simulation"))
        self.label_4.setText(_translate("PottsGUI", "Anneal Steps"))
        self.label_5.setText(_translate("PottsGUI", "Flips per Site"))
        self.random_seed_CB.setText(_translate("PottsGUI", "Random Seed"))
        self.debug_CB.setText(_translate("PottsGUI", "Debug Output Frequency"))
        self.groupBox_4.setTitle(_translate("PottsGUI", "Energy Function Calculator"))
        self.ef_results_CB.setText(_translate("PottsGUI", "Results"))
        self.ef_enable_CB.setText(_translate("PottsGUI", "Enable"))
        self.ef_accepted_CB.setText(_translate("PottsGUI", "Accepted"))
        self.ef_rejected_CB.setText(_translate("PottsGUI", "Rejected"))
        self.ef_total_CB.setText(_translate("PottsGUI", "Total"))
        self.label_10.setText(_translate("PottsGUI", "Spin Flip Frequency"))
        self.label_9.setText(_translate("PottsGUI", "File Name"))
        self.ef_file_name_LE.setText(_translate("PottsGUI", "statData.txt"))
        self.label_8.setText(_translate("PottsGUI", "Output Frequency"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advanced), _translate("PottsGUI", "Advanced"))
