# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pottsdlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PottsGUI(object):
    def setupUi(self, PottsGUI):
        PottsGUI.setObjectName("PottsGUI")
        PottsGUI.resize(308, 323)
        self.gridLayout = QtWidgets.QGridLayout(PottsGUI)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.groupBox_7 = QtWidgets.QGroupBox(PottsGUI)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_28 = QtWidgets.QLabel(self.groupBox_7)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_24.addWidget(self.label_28)
        self.xDimSB = QtWidgets.QSpinBox(self.groupBox_7)
        self.xDimSB.setMinimum(1)
        self.xDimSB.setMaximum(10000000)
        self.xDimSB.setProperty("value", 256)
        self.xDimSB.setObjectName("xDimSB")
        self.horizontalLayout_24.addWidget(self.xDimSB)
        self.label_29 = QtWidgets.QLabel(self.groupBox_7)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_24.addWidget(self.label_29)
        self.yDimSB = QtWidgets.QSpinBox(self.groupBox_7)
        self.yDimSB.setMinimum(1)
        self.yDimSB.setMaximum(10000000)
        self.yDimSB.setProperty("value", 256)
        self.yDimSB.setObjectName("yDimSB")
        self.horizontalLayout_24.addWidget(self.yDimSB)
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_24.addWidget(self.label_30)
        self.zDimSB = QtWidgets.QSpinBox(self.groupBox_7)
        self.zDimSB.setMinimum(1)
        self.zDimSB.setMaximum(10000000)
        self.zDimSB.setObjectName("zDimSB")
        self.horizontalLayout_24.addWidget(self.zDimSB)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_24)
        self.verticalLayout_19.addWidget(self.groupBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(PottsGUI)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.xbcCB = QtWidgets.QComboBox(self.groupBox_3)
        self.xbcCB.setObjectName("xbcCB")
        self.xbcCB.addItem("")
        self.xbcCB.addItem("")
        self.horizontalLayout_11.addWidget(self.xbcCB)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.ybcCB = QtWidgets.QComboBox(self.groupBox_3)
        self.ybcCB.setObjectName("ybcCB")
        self.ybcCB.addItem("")
        self.ybcCB.addItem("")
        self.horizontalLayout_11.addWidget(self.ybcCB)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.zbcCB = QtWidgets.QComboBox(self.groupBox_3)
        self.zbcCB.setObjectName("zbcCB")
        self.zbcCB.addItem("")
        self.zbcCB.addItem("")
        self.horizontalLayout_11.addWidget(self.zbcCB)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_19.addWidget(self.groupBox_3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_33 = QtWidgets.QLabel(PottsGUI)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(PottsGUI)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 0, 1, 1)
        self.mcsSB = QtWidgets.QSpinBox(PottsGUI)
        self.mcsSB.setMaximum(1000000000)
        self.mcsSB.setProperty("value", 100000)
        self.mcsSB.setObjectName("mcsSB")
        self.gridLayout_6.addWidget(self.mcsSB, 5, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(PottsGUI)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 0, 0, 1, 1)
        self.latticeTypeCB = QtWidgets.QComboBox(PottsGUI)
        self.latticeTypeCB.setObjectName("latticeTypeCB")
        self.latticeTypeCB.addItem("")
        self.latticeTypeCB.addItem("")
        self.gridLayout_6.addWidget(self.latticeTypeCB, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(PottsGUI)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 4, 0, 1, 1)
        self.fluctuation_FcnCB = QtWidgets.QComboBox(PottsGUI)
        self.fluctuation_FcnCB.setObjectName("fluctuation_FcnCB")
        self.gridLayout_6.addWidget(self.fluctuation_FcnCB, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(PottsGUI)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 3, 0, 1, 1)
        self.membraneFluctuationsLE = QtWidgets.QLineEdit(PottsGUI)
        self.membraneFluctuationsLE.setObjectName("membraneFluctuationsLE")
        self.gridLayout_6.addWidget(self.membraneFluctuationsLE, 3, 1, 1, 1)
        self.neighborOrderSB = QtWidgets.QSpinBox(PottsGUI)
        self.neighborOrderSB.setMinimum(1)
        self.neighborOrderSB.setMaximum(10)
        self.neighborOrderSB.setProperty("value", 1)
        self.neighborOrderSB.setObjectName("neighborOrderSB")
        self.gridLayout_6.addWidget(self.neighborOrderSB, 4, 1, 1, 1)
        self.cell_TypeCB = QtWidgets.QComboBox(PottsGUI)
        self.cell_TypeCB.setObjectName("cell_TypeCB")
        self.gridLayout_6.addWidget(self.cell_TypeCB, 2, 0, 1, 1)
        self.type_ParamLE = QtWidgets.QLineEdit(PottsGUI)
        self.type_ParamLE.setObjectName("type_ParamLE")
        self.gridLayout_6.addWidget(self.type_ParamLE, 2, 1, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(PottsGUI)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_19.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout_19, 0, 0, 1, 1)

        self.retranslateUi(PottsGUI)
        QtCore.QMetaObject.connectSlotsByName(PottsGUI)

    def retranslateUi(self, PottsGUI):
        _translate = QtCore.QCoreApplication.translate
        PottsGUI.setWindowTitle(_translate("PottsGUI", "Potts: Please define CPM configuration"))
        self.groupBox_7.setTitle(_translate("PottsGUI", "Lattice Dimensions"))
        self.label_28.setText(_translate("PottsGUI", "x"))
        self.label_29.setText(_translate("PottsGUI", "y"))
        self.label_30.setText(_translate("PottsGUI", "z"))
        self.groupBox_3.setTitle(_translate("PottsGUI", "Boundary Conditions (Cell Lattice)"))
        self.label_13.setText(_translate("PottsGUI", "x"))
        self.xbcCB.setItemText(0, _translate("PottsGUI", "NoFlux"))
        self.xbcCB.setItemText(1, _translate("PottsGUI", "Periodic"))
        self.label_14.setText(_translate("PottsGUI", "y"))
        self.ybcCB.setItemText(0, _translate("PottsGUI", "NoFlux"))
        self.ybcCB.setItemText(1, _translate("PottsGUI", "Periodic"))
        self.label_15.setText(_translate("PottsGUI", "z"))
        self.zbcCB.setItemText(0, _translate("PottsGUI", "NoFlux"))
        self.zbcCB.setItemText(1, _translate("PottsGUI", "Periodic"))
        self.label_33.setText(_translate("PottsGUI", "Number of MC Steps"))
        self.label.setText(_translate("PottsGUI", "Fluctuation Function"))
        self.label_44.setText(_translate("PottsGUI", "LatticeType"))
        self.latticeTypeCB.setItemText(0, _translate("PottsGUI", "Square"))
        self.latticeTypeCB.setItemText(1, _translate("PottsGUI", "Hexagonal"))
        self.label_32.setText(_translate("PottsGUI", "Pixel Copy Range (NeighborOrder)"))
        self.label_31.setText(_translate("PottsGUI", "Average Membrane Fluctuations"))
        self.membraneFluctuationsLE.setToolTip(_translate("PottsGUI", "Also known as so called temperature parameter in the acceptance probability expresion:  exp(-delta E/(k*T))"))
        self.membraneFluctuationsLE.setText(_translate("PottsGUI", "10"))
