/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CalculatorPack;

public class Calculator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Calculator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Calculator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      classesJNI.delete_Calculator(swigCPtr);
    }
    swigCPtr = 0;
  }

  public Calculator() {
    this(classesJNI.new_Calculator(), true);
  }

  public void calculate(int _max) {
    classesJNI.Calculator_calculate(swigCPtr, this, _max);
  }

}
