/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CalculatorPack;

class classesJNI {
  public final static native long new_Calculator();
  public final static native void delete_Calculator(long jarg1);
  public final static native void Calculator_calculate(long jarg1, Calculator jarg1_, int jarg2);
}
