        
#include "ClusterSurfaceTrackerPlugin.h"

#include <CompuCell3D/Simulator.h>
using namespace CompuCell3D;

#include <BasicUtils/BasicPluginProxy.h>

BasicPluginProxy<Plugin, ClusterSurfaceTrackerPlugin>
clusterSurfaceTrackerProxy("ClusterSurfaceTracker", "Autogenerated plugin - the author of the plugin should provide brief description here",
         &Simulator::pluginManager);
