        
#include "Polarization23Plugin.h"

#include <CompuCell3D/Simulator.h>
using namespace CompuCell3D;

#include <BasicUtils/BasicPluginProxy.h>

BasicPluginProxy<Plugin, Polarization23Plugin>
polarization23Proxy("Polarization23", "Autogenerated plugin - the author of the plugin should provide brief description here",
         &Simulator::pluginManager);
