# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ncmaterialsdlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NCMaterialsDlg(object):
    def setupUi(self, NCMaterialsDlg):
        NCMaterialsDlg.setObjectName("NCMaterialsDlg")
        NCMaterialsDlg.resize(725, 437)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NCMaterialsDlg.sizePolicy().hasHeightForWidth())
        NCMaterialsDlg.setSizePolicy(sizePolicy)
        NCMaterialsDlg.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(NCMaterialsDlg)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_materialDefs = QtWidgets.QTableWidget(NCMaterialsDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_materialDefs.sizePolicy().hasHeightForWidth())
        self.tableWidget_materialDefs.setSizePolicy(sizePolicy)
        self.tableWidget_materialDefs.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidget_materialDefs.setObjectName("tableWidget_materialDefs")
        self.tableWidget_materialDefs.setColumnCount(3)
        self.tableWidget_materialDefs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_materialDefs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_materialDefs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_materialDefs.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget_materialDefs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(NCMaterialsDlg)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(NCMaterialsDlg)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox = QtWidgets.QCheckBox(NCMaterialsDlg)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.pushButton_add = QtWidgets.QPushButton(NCMaterialsDlg)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_delete = QtWidgets.QPushButton(NCMaterialsDlg)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_2.addWidget(self.pushButton_delete)
        self.pushButton_clear = QtWidgets.QPushButton(NCMaterialsDlg)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_2.addWidget(self.pushButton_clear)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(NCMaterialsDlg)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_adhesion = QtWidgets.QWidget()
        self.tab_adhesion.setObjectName("tab_adhesion")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_adhesion)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_adhesion = QtWidgets.QTableWidget(self.tab_adhesion)
        self.tableWidget_adhesion.setObjectName("tableWidget_adhesion")
        self.tableWidget_adhesion.setColumnCount(0)
        self.tableWidget_adhesion.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget_adhesion, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_adhesion, "")
        self.tab_remodeling = QtWidgets.QWidget()
        self.tab_remodeling.setObjectName("tab_remodeling")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_remodeling)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_remodeling = QtWidgets.QTableWidget(self.tab_remodeling)
        self.tableWidget_remodeling.setObjectName("tableWidget_remodeling")
        self.tableWidget_remodeling.setColumnCount(0)
        self.tableWidget_remodeling.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_remodeling, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_remodeling, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(NCMaterialsDlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(NCMaterialsDlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NCMaterialsDlg)

    def retranslateUi(self, NCMaterialsDlg):
        _translate = QtCore.QCoreApplication.translate
        NCMaterialsDlg.setWindowTitle(_translate("NCMaterialsDlg", "NCMaterials Plugin: Please define noncellular materials"))
        item = self.tableWidget_materialDefs.horizontalHeaderItem(0)
        item.setText(_translate("NCMaterialsDlg", "NCMaterial"))
        item = self.tableWidget_materialDefs.horizontalHeaderItem(1)
        item.setText(_translate("NCMaterialsDlg", "Advects"))
        item = self.tableWidget_materialDefs.horizontalHeaderItem(2)
        item.setText(_translate("NCMaterialsDlg", "Durability coeff."))
        self.label.setText(_translate("NCMaterialsDlg", "NCMaterial"))
        self.checkBox.setText(_translate("NCMaterialsDlg", "Advects"))
        self.pushButton_add.setText(_translate("NCMaterialsDlg", "Add"))
        self.pushButton_delete.setText(_translate("NCMaterialsDlg", "Delete NCMaterial"))
        self.pushButton_clear.setText(_translate("NCMaterialsDlg", "Clear Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adhesion), _translate("NCMaterialsDlg", "Adhesion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_remodeling), _translate("NCMaterialsDlg", "Remodeling"))
