#include "BoundaryMonitorPlugin.h"

#include <CompuCell3D/Simulator.h>
#include <CompuCell3D/PluginManager.h>

using namespace CompuCell3D;

auto boundaryMonitorProxy = registerPlugin<Plugin, BoundaryMonitorPlugin>(
        "BoundaryMonitor",
        "Autogenerated plugin - the author of the plugin should provide brief description here",
        &Simulator::pluginManager
);
